<?php declare(strict_types=1);

namespace Apc\Services;

use Apc\Repositories\{AuditRepository,CurriculumRepository};
use Apc\Support\Input;
use Shared\Exceptions\HttpException;

final class CurriculumService
{
    private const STAGES=['EF_AI','EF_AF','EM'];
    private const YEARS=['EF1','EF2','EF3','EF4','EF5','EF6','EF7','EF8','EF9','EM1','EM2','EM3'];
    public function __construct(private readonly CurriculumRepository $curriculum,private readonly AuditRepository $audit) {}

    public function saveComponent(?int $id,array $input,array $user,string $ip,string $agent): int
    {
        $this->admin($user);$data=['nome'=>Input::text($input['nome']??null,'Nome',160),'sigla'=>Input::text($input['sigla']??null,'Sigla',30),'modalidade'=>$this->choice($input['modalidade']??'GERAL',['GERAL','EDUCACAO_DO_CAMPO'],'Modalidade'),'etapa'=>$this->choice($input['etapa']??'',['EF_AI','EF_AF','EM'],'Etapa'),'area_conhecimento'=>Input::text($input['area_conhecimento']??null,'Área do conhecimento',120),'ordem'=>filter_var($input['ordem']??0,FILTER_VALIDATE_INT)!==false?(int)$input['ordem']:0,'ativo'=>array_key_exists('ativo',$input)&&((int)$input['ativo'])!==0?1:0];$db=$this->curriculum->db;$db->beginTransaction();try{if($id===null){$data['chave']='MANUAL_'.bin2hex(random_bytes(12));$id=$this->curriculum->upsertComponent($data);$action='COMPONENTE_CRIADO';$before=null;}else{$before=$this->curriculum->component($id)??throw new HttpException(404,'APC_COMPONENT_NOT_FOUND','Componente não encontrado.');$this->curriculum->updateComponent($id,$data);$action=$data['ativo']?'COMPONENTE_EDITADO':'COMPONENTE_DESATIVADO';}$this->audit->record((int)$user['id'],$action,'apc_componentes_curriculares',$id,$before,$data,$ip,$agent);$db->commit();return$id;}catch(\Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}}

    public function saveAbility(?int $id,array $input,array $user,string $ip,string $agent): int
    {
        $this->admin($user);$componentId=Input::positiveInt($input['componente_id']??null);$component=$this->curriculum->component($componentId)??throw new HttpException(422,'APC_COMPONENT_NOT_FOUND','Componente não encontrado.');$code=trim((string)($input['codigo']??''));if(mb_strlen($code)>80)throw new HttpException(422,'APC_INVALID_CURRICULUM','Código muito longo.');$data=['componente_id'=>$componentId,'codigo'=>$code===''?null:$code,'descricao'=>Input::text($input['descricao']??null,'Descrição',12000),'unidade_tematica'=>Input::text($input['unidade_tematica']??'','Unidade temática',1000,false),'objeto_conhecimento'=>Input::text($input['objeto_conhecimento']??'','Objeto de conhecimento',4000,false),'origem'=>Input::text($input['origem']??'OUTRO_OFICIAL','Origem',120),'escopo'=>Input::text($input['escopo']??'CURRICULO_COMPLETO','Escopo',120),'fonte_documento'=>Input::text($input['fonte_documento']??'CADASTRO_MANUAL','Fonte',255),'fonte_pagina'=>trim((string)($input['fonte_pagina']??''))===''?null:Input::positiveInt($input['fonte_pagina']),'ativo'=>array_key_exists('ativo',$input)&&((int)$input['ativo'])!==0?1:0];$tokens=array_values(array_unique(array_map('strval',(array)($input['associacoes']??[]))));if(!$tokens){$type=$this->choice($input['tipo_associacao']??'CURRICULAR',['CURRICULAR','RECOMPOSICAO'],'Tipo de associação');$tokens=array_map(static fn($year):string=>(string)$year.'|'.$type,(array)($input['anos_series']??[]));}if(!$tokens)throw new HttpException(422,'APC_INVALID_CURRICULUM','Selecione ao menos uma associação de ano/série.');$associations=[];foreach($tokens as$token){[$year,$type]=array_pad(explode('|',$token,2),2,'');if(!in_array($year,self::YEARS,true))throw new HttpException(422,'APC_INVALID_CURRICULUM','Ano/série inválido.');$type=$this->choice($type,['CURRICULAR','RECOMPOSICAO'],'Tipo de associação');$associations[]=['etapa'=>$this->stageForYear($year),'ano_serie'=>$year,'tipo_associacao'=>$type];}$db=$this->curriculum->db;$db->beginTransaction();try{if($id===null){$data['chave_estavel']='MANUAL_'.bin2hex(random_bytes(16));$id=$this->curriculum->upsertAbility($data);$before=null;$action='HABILIDADE_CRIADA';}else{$before=$this->curriculum->ability($id)??throw new HttpException(404,'APC_ABILITY_NOT_FOUND','Habilidade não encontrada.');$this->curriculum->updateAbility($id,$data);$action=$data['ativo']?'HABILIDADE_EDITADA':'HABILIDADE_DESATIVADA';}$this->curriculum->syncAbilityAssociations($id,$associations);$this->audit->record((int)$user['id'],$action,'apc_habilidades_curriculares',$id,$before,$data+['associacoes'=>$associations],$ip,$agent);$db->commit();return$id;}catch(\Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}}

    public function toggleComponent(int $id,array $user,string $ip,string $agent): void{$this->admin($user);$before=$this->curriculum->component($id)??throw new HttpException(404,'APC_COMPONENT_NOT_FOUND','Componente não encontrado.');$active=!(bool)$before['ativo'];$this->toggle($user,'apc_componentes_curriculares',$id,$before,$active?'COMPONENTE_ATIVADO':'COMPONENTE_DESATIVADO',$ip,$agent,fn()=>$this->curriculum->setComponentActive($id,$active));}
    public function toggleAbility(int $id,array $user,string $ip,string $agent): void{$this->admin($user);$before=$this->curriculum->ability($id)??throw new HttpException(404,'APC_ABILITY_NOT_FOUND','Habilidade não encontrada.');$active=!(bool)$before['ativo'];$this->toggle($user,'apc_habilidades_curriculares',$id,$before,$active?'HABILIDADE_ATIVADA':'HABILIDADE_DESATIVADA',$ip,$agent,fn()=>$this->curriculum->setAbilityActive($id,$active));}
    private function toggle(array$user,string$entity,int$id,array$before,string$action,string$ip,string$agent,callable$change):void{$db=$this->curriculum->db;$db->beginTransaction();try{$change();$this->audit->record((int)$user['id'],$action,$entity,$id,['ativo'=>(int)$before['ativo']],['ativo'=>(int)!$before['ativo']],$ip,$agent);$db->commit();}catch(\Throwable$e){if($db->inTransaction())$db->rollBack();throw$e;}}
    private function admin(array$user):void{if(($user['perfil']??'')!=='ADMIN')throw new HttpException(403,'APC_FORBIDDEN','Apenas a administração pode alterar o catálogo curricular.');}
    private function choice(mixed$value,array$allowed,string$label):string{$value=trim((string)$value);if(!in_array($value,$allowed,true))throw new HttpException(422,'APC_INVALID_CURRICULUM',"$label inválida.");return$value;}
    private function stageForYear(string$year):string{return str_starts_with($year,'EM')?'EM':((int)substr($year,2)<=5?'EF_AI':'EF_AF');}
}
