<?php declare(strict_types=1);
namespace PreConselho\Services;
use PreConselho\Repositories\AppRepository;use Shared\Exceptions\HttpException;
final class PeriodService
{
 public function __construct(private readonly AppRepository$r){}
 public function create(array$d,int$user,string$ip,string$ua):int{$name=trim((string)($d['nome']??''));$year=filter_var($d['ano_letivo']??null,FILTER_VALIDATE_INT);$stage=trim((string)($d['etapa']??''));$start=$this->date($d['data_inicio']??'');$end=$this->date($d['data_fim']??'');if($name===''||mb_strlen($name)>150||!$year||$year<2000||$year>2100||$stage===''||$end<$start)throw new HttpException(422,'VALIDATION_ERROR','Dados do período inválidos.');$s=$this->r->db->prepare('INSERT INTO periodos_pre_conselho(nome,ano_letivo,etapa,data_inicio,data_fim,criado_por)VALUES(:n,:a,:e,:i,:f,:u)');$s->execute([':n'=>$name,':a'=>$year,':e'=>$stage,':i'=>$start,':f'=>$end,':u'=>$user]);$id=(int)$this->r->db->lastInsertId();$this->r->audit($user,'CRIAR','periodos_pre_conselho',$id,null,$d,$ip,$ua);return$id;}
 public function open(int$id,int$user,string$ip,string$ua):void{$this->r->db->beginTransaction();try{$s=$this->r->db->prepare("SELECT * FROM periodos_pre_conselho WHERE id=:id");$s->execute([':id'=>$id]);$p=$s->fetch()?:throw new HttpException(404,'NOT_FOUND','Período não encontrado.');if($p['status']!=='RASCUNHO')throw new HttpException(422,'INVALID_STATUS','Somente períodos em rascunho podem ser abertos.');$this->r->db->prepare("INSERT OR IGNORE INTO relatorios_pre_conselho(periodo_id,vinculo_id) SELECT :p,id FROM vinculos_professor_turma_disciplina WHERE ativo=1 AND turma_ano_letivo_snapshot=:a")->execute([':p'=>$id,':a'=>$p['ano_letivo']]);$this->r->db->prepare("UPDATE periodos_pre_conselho SET status='ABERTO',atualizado_em=CURRENT_TIMESTAMP WHERE id=:id")->execute([':id'=>$id]);$this->r->audit($user,'ABRIR','periodos_pre_conselho',$id,['status'=>'RASCUNHO'],['status'=>'ABERTO'],$ip,$ua);$this->r->db->commit();}catch(\Throwable$e){if($this->r->db->inTransaction())$this->r->db->rollBack();throw$e;}}
 public function close(int$id,int$user,string$ip,string$ua):void{$s=$this->r->db->prepare("UPDATE periodos_pre_conselho SET status='ENCERRADO',encerrado_por=:u,encerrado_em=CURRENT_TIMESTAMP,atualizado_em=CURRENT_TIMESTAMP WHERE id=:id AND status='ABERTO'");$s->execute([':u'=>$user,':id'=>$id]);if($s->rowCount()!==1)throw new HttpException(422,'INVALID_STATUS','Período não pode ser encerrado.');$this->r->audit($user,'ENCERRAR','periodos_pre_conselho',$id,['status'=>'ABERTO'],['status'=>'ENCERRADO'],$ip,$ua);}
 private function date(mixed$v):string{$d=\DateTimeImmutable::createFromFormat('!Y-m-d',(string)$v);if(!$d||$d->format('Y-m-d')!==$v)throw new HttpException(422,'VALIDATION_ERROR','Data inválida.');return$d->format('Y-m-d');}
}
