<?php declare(strict_types=1);

namespace Tests;

use Apc\Controllers\SubmissionController;
use Apc\Repositories\{AccessRepository,AuditRepository,EventRepository,SubmissionRepository,TermRepository};
use Apc\Services\SubmissionService;
use Shared\Http\Request;
use Shared\Support\View;

final class ApcSubmissionDashboardTest extends ApcTestCase
{
    protected function tearDown():void{unset($_SESSION['user'],$_SESSION['_csrf']);$_SERVER['REQUEST_URI']='/';}

    public function testLocalFilePreviewKeepsInactiveRenderersHidden():void
    {
        $css=(string)file_get_contents(dirname(__DIR__).'/apps/preconselho-web/public/assets/app.css');
        self::assertStringContainsString('.apc-local-preview>[hidden]{display:none!important}',$css);
    }

    public function testTeacherSeesOnlySimpleUploadFieldsFromCouncilBindings():void
    {
        $main=$this->mainDatabase();$this->seedMain($main);$apc=$this->apcDatabase();$this->seedEvent($apc);$apc->exec("INSERT INTO apc_eventos(id,ano_letivo,data,titulo,tipo,origem,descricao,status,criado_por)VALUES(2,2026,'2026-10-10','APC de outubro','OUTRO','ESCOLA','Próximo evento','ATIVO',1)");$repository=new SubmissionRepository($apc);$access=new AccessRepository($main);$controller=new SubmissionController(new SubmissionService($repository,new EventRepository($apc),new TermRepository($apc),$access,new AuditRepository($apc),sys_get_temp_dir(),1048576,null,null,'2026-08-11'),$repository,$access,new View(dirname(__DIR__).'/apps/apc/resources/views'));$_SESSION['user']=['id'=>3,'nome'=>'Professor Um','perfil'=>'PROFESSOR'];$_SERVER['REQUEST_URI']='/apc';$response=$controller->index(new Request('GET','/apc',[],[],[]));self::assertStringContainsString('APCs disponíveis agora',$response->body);self::assertStringContainsString('Concluídas: 0 de 2',$response->body);self::assertStringContainsString('APC de agosto',$response->body);self::assertStringContainsString('APC de outubro',$response->body);self::assertStringContainsString('Aguardando envio',$response->body);self::assertStringContainsString('disponível automaticamente enquanto o evento estiver ativo',$response->body);self::assertStringNotContainsString('aguardando liberação',$response->body);self::assertStringNotContainsString('A coordenação ainda não abriu este envio',$response->body);self::assertStringContainsString('Anexar o modelo pronto',$response->body);self::assertStringContainsString('name="evento_id"',$response->body);self::assertStringContainsString('name="etapa"',$response->body);self::assertStringContainsString('name="ano_serie"',$response->body);self::assertStringContainsString('name="turma_id"',$response->body);self::assertStringContainsString('name="arquivo"',$response->body);self::assertStringContainsString('data-apc-upload-review',$response->body);self::assertStringContainsString('Pré-visualização do arquivo',$response->body);self::assertStringContainsString('data-apc-preview-pdf',$response->body);self::assertStringContainsString('data-apc-preview-image',$response->body);self::assertStringContainsString('Confirmar e enviar APC',$response->body);self::assertStringContainsString('7º ano',$response->body);self::assertStringContainsString('7º A',$response->body);self::assertStringNotContainsString('Componentes curriculares',$response->body);self::assertStringNotContainsString('Entregas dos alunos',$response->body);
    }

    public function testAttachedAndLateStatusesRemainVisibleAfterUpload():void
    {
        $main=$this->mainDatabase();$this->seedMain($main);$apc=$this->apcDatabase();$this->seedEvent($apc);$apc->exec("INSERT INTO apc_envios(id,evento_id,bimestre_id,professor_usuario_id,professor_nome_snapshot,etapa,ano_serie,nome_original,nome_armazenado,mime_type,tamanho_bytes,sha256,caminho_relativo,atrasado,dias_atraso,enviado_em)VALUES(1,1,3,3,'Professor Um','EF_AF','EF7','modelo-apc.pdf','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf','application/pdf',1200,'".str_repeat('b',64)."','envios/2026/08/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf',1,5,'2026-08-20 10:00:00');INSERT INTO apc_envio_turmas(envio_id,turma_id_externo,turma_nome_snapshot)VALUES(1,10,'7º A')");$repository=new SubmissionRepository($apc);$access=new AccessRepository($main);$controller=new SubmissionController(new SubmissionService($repository,new EventRepository($apc),new TermRepository($apc),$access,new AuditRepository($apc),sys_get_temp_dir(),1048576,null,null,'2026-08-20'),$repository,$access,new View(dirname(__DIR__).'/apps/apc/resources/views'));$_SESSION['user']=['id'=>3,'nome'=>'Professor Um','perfil'=>'PROFESSOR'];$_SERVER['REQUEST_URI']='/apc';$response=$controller->index(new Request('GET','/apc',[],[],[]));self::assertStringContainsString('Arquivo anexado',$response->body);self::assertStringContainsString('Entregue com atraso · 5 dia(s)',$response->body);self::assertStringContainsString('modelo-apc.pdf',$response->body);self::assertStringContainsString('7º A',$response->body);self::assertStringContainsString('/apc/envios/1/visualizar',$response->body);self::assertStringContainsString('Visualizar APC',$response->body);self::assertStringContainsString('Tudo certo! Você concluiu todas as APCs disponíveis no momento',$response->body);self::assertStringContainsString('Envio concluído',$response->body);self::assertStringContainsString('Todas as APCs disponíveis já foram anexadas',$response->body);self::assertStringNotContainsString('data-apc-submission',$response->body);self::assertStringNotContainsString('/apc/envios/1/excluir',$response->body);
    }

    public function testTeacherWithAnotherPendingSeriesKeepsOnlyPendingCombinationAvailable():void
    {
        $main=$this->mainDatabase();$this->seedMain($main);$main->exec("INSERT INTO vinculos_professor_turma(id,professor_id,turma_externa_id,turma_nome_snapshot,turma_ano_letivo_snapshot,turno)VALUES(3,1,30,'8º B',2026,'MATUTINO')");$apc=$this->apcDatabase();$this->seedEvent($apc);$apc->exec("INSERT INTO apc_envios(id,evento_id,bimestre_id,professor_usuario_id,professor_nome_snapshot,etapa,ano_serie,nome_original,nome_armazenado,mime_type,tamanho_bytes,sha256,caminho_relativo,atrasado,dias_atraso,enviado_em)VALUES(1,1,3,3,'Professor Um','EF_AF','EF7','apc-7.pdf','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf','application/pdf',1200,'".str_repeat('b',64)."','envios/2026/08/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf',0,0,'2026-08-11 10:00:00');INSERT INTO apc_envio_turmas(envio_id,turma_id_externo,turma_nome_snapshot)VALUES(1,10,'7º A')");$repository=new SubmissionRepository($apc);$access=new AccessRepository($main);$controller=new SubmissionController(new SubmissionService($repository,new EventRepository($apc),new TermRepository($apc),$access,new AuditRepository($apc),sys_get_temp_dir(),1048576,null,null,'2026-08-11'),$repository,$access,new View(dirname(__DIR__).'/apps/apc/resources/views'));$_SESSION['user']=['id'=>3,'nome'=>'Professor Um','perfil'=>'PROFESSOR'];$_SERVER['REQUEST_URI']='/apc';$response=$controller->index(new Request('GET','/apc',[],[],[]));self::assertStringContainsString('Envio parcial',$response->body);self::assertStringContainsString('Falta enviar:',$response->body);self::assertStringContainsString('8º B',$response->body);self::assertStringContainsString('data-choose-apc-event="1"',$response->body);self::assertStringContainsString('data-apc-submission',$response->body);self::assertMatchesRegularExpression('/value="10"[^>]+data-year="EF7"[^>]+data-submitted-events="1"/',$response->body);self::assertMatchesRegularExpression('/value="30"[^>]+data-year="EF8"[^>]+data-submitted-events=""/',$response->body);self::assertStringContainsString('não poderão ser enviados novamente',$response->body);
    }

    public function testOneClassSubmissionDoesNotCompleteOtherClassFromSameSeries():void
    {
        $main=$this->mainDatabase();$this->seedMain($main);$main->exec("INSERT INTO vinculos_professor_turma(id,professor_id,turma_externa_id,turma_nome_snapshot,turma_ano_letivo_snapshot,turno)VALUES(3,1,30,'7º B',2026,'MATUTINO')");
        $apc=$this->apcDatabase();$this->seedEvent($apc);$apc->exec("INSERT INTO apc_envios(id,evento_id,bimestre_id,professor_usuario_id,professor_nome_snapshot,etapa,ano_serie,nome_original,nome_armazenado,mime_type,tamanho_bytes,sha256,caminho_relativo,atrasado,dias_atraso,enviado_em)VALUES(1,1,3,3,'Professor Um','EF_AF','EF7','apc-7a.pdf','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf','application/pdf',1200,'".str_repeat('b',64)."','envios/2026/08/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf',0,0,'2026-08-11 10:00:00');INSERT INTO apc_envio_turmas(envio_id,turma_id_externo,turma_nome_snapshot)VALUES(1,10,'7º A')");
        $repository=new SubmissionRepository($apc);$access=new AccessRepository($main);$controller=new SubmissionController(new SubmissionService($repository,new EventRepository($apc),new TermRepository($apc),$access,new AuditRepository($apc),sys_get_temp_dir(),1048576,null,null,'2026-08-11'),$repository,$access,new View(dirname(__DIR__).'/apps/apc/resources/views'));

        $_SESSION['user']=['id'=>3,'nome'=>'Professor Um','perfil'=>'PROFESSOR'];$_SERVER['REQUEST_URI']='/apc';$teacher=$controller->index(new Request('GET','/apc',[],[],[]));
        self::assertStringContainsString('Turmas enviadas: 1 de 2',$teacher->body);self::assertStringContainsString('Falta enviar:</strong><span>7º B',$teacher->body);self::assertMatchesRegularExpression('/value="30"[^>]+data-year="EF7"[^>]+data-submitted-events=""/',$teacher->body);self::assertStringNotContainsString('Todas as APCs disponíveis já foram anexadas',$teacher->body);

        $_SESSION['user']=['id'=>2,'nome'=>'Coordenação','perfil'=>'COORDENADOR'];$coordination=$controller->index(new Request('GET','/apc',[],[],[]));
        self::assertStringContainsString('Professor Um',$coordination->body);self::assertStringContainsString('1 de 2 turma(s) enviada(s)',$coordination->body);self::assertStringContainsString('<span>7º B</span>',$coordination->body);self::assertStringContainsString('Envio parcial',$coordination->body);
    }

    public function testLegacySubmissionLinkedAutomaticallyToMultipleClassesDoesNotCompleteThem():void
    {
        $main=$this->mainDatabase();$this->seedMain($main);$main->exec("INSERT INTO vinculos_professor_turma(id,professor_id,turma_externa_id,turma_nome_snapshot,turma_ano_letivo_snapshot,turno)VALUES(3,1,30,'7º B',2026,'MATUTINO')");
        $apc=$this->apcDatabase();$this->seedEvent($apc);$apc->exec("INSERT INTO apc_envios(id,evento_id,bimestre_id,professor_usuario_id,professor_nome_snapshot,etapa,ano_serie,nome_original,nome_armazenado,mime_type,tamanho_bytes,sha256,caminho_relativo,atrasado,dias_atraso,enviado_em)VALUES(1,1,3,3,'Professor Um','EF_AF','EF7','apc-antiga.pdf','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf','application/pdf',1200,'".str_repeat('b',64)."','envios/2026/08/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf',0,0,'2026-08-11 10:00:00');INSERT INTO apc_envio_turmas(envio_id,turma_id_externo,turma_nome_snapshot)VALUES(1,10,'7º A'),(1,30,'7º B')");
        $repository=new SubmissionRepository($apc);$access=new AccessRepository($main);$controller=new SubmissionController(new SubmissionService($repository,new EventRepository($apc),new TermRepository($apc),$access,new AuditRepository($apc),sys_get_temp_dir(),1048576,null,null,'2026-08-11'),$repository,$access,new View(dirname(__DIR__).'/apps/apc/resources/views'));

        $_SESSION['user']=['id'=>3,'nome'=>'Professor Um','perfil'=>'PROFESSOR'];$_SERVER['REQUEST_URI']='/apc';$teacher=$controller->index(new Request('GET','/apc',[],[],[]));
        self::assertStringContainsString('Turmas enviadas: 0 de 2',$teacher->body);self::assertMatchesRegularExpression('/value="10"[^>]+data-submitted-events=""/',$teacher->body);self::assertMatchesRegularExpression('/value="30"[^>]+data-submitted-events=""/',$teacher->body);

        $_SESSION['user']=['id'=>2,'nome'=>'Coordenação','perfil'=>'COORDENADOR'];$coordination=$controller->index(new Request('GET','/apc',[],[],[]));
        self::assertStringContainsString('Professor Um',$coordination->body);self::assertStringContainsString('0 de 2 turma(s) enviada(s)',$coordination->body);self::assertStringContainsString('Ainda não enviou',$coordination->body);
    }

    public function testCoordinationGroupsMultipleFilesUnderOneCollapsedProfessor():void
    {
        $main=$this->mainDatabase();$this->seedMain($main);$main->exec("INSERT INTO vinculos_professor_turma(id,professor_id,turma_externa_id,turma_nome_snapshot,turma_ano_letivo_snapshot,turno)VALUES(3,1,11,'7º B',2026,'MATUTINO'),(4,1,12,'7º C',2026,'MATUTINO')");
        $apc=$this->apcDatabase();$this->seedEvent($apc);$apc->exec("INSERT INTO apc_envios(id,evento_id,bimestre_id,professor_usuario_id,professor_nome_snapshot,etapa,ano_serie,turma_id_externo,nome_original,nome_armazenado,mime_type,tamanho_bytes,sha256,caminho_relativo,atrasado,dias_atraso,enviado_em)VALUES(1,1,3,3,'Professor Um','EF_AF','EF7',10,'apc-7a.pdf','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf','application/pdf',1200,'".str_repeat('a',64)."','envios/2026/08/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf',0,0,'2026-08-11 10:00:00'),(2,1,3,3,'Professor Um','EF_AF','EF7',11,'apc-7b.pdf','bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.pdf','application/pdf',1300,'".str_repeat('b',64)."','envios/2026/08/bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb.pdf',0,0,'2026-08-11 10:05:00'),(3,1,3,3,'Professor Um','EF_AF','EF7',12,'apc-7c.pdf','cccccccccccccccccccccccccccccccc.pdf','application/pdf',1400,'".str_repeat('c',64)."','envios/2026/08/cccccccccccccccccccccccccccccccc.pdf',1,2,'2026-08-17 10:10:00');INSERT INTO apc_envio_turmas(envio_id,turma_id_externo,turma_nome_snapshot)VALUES(1,10,'7º A'),(2,11,'7º B'),(3,12,'7º C')");
        $repository=new SubmissionRepository($apc);$access=new AccessRepository($main);$controller=new SubmissionController(new SubmissionService($repository,new EventRepository($apc),new TermRepository($apc),$access,new AuditRepository($apc),sys_get_temp_dir(),1048576,null,null,'2026-08-20'),$repository,$access,new View(dirname(__DIR__).'/apps/apc/resources/views'));$_SESSION['user']=['id'=>2,'nome'=>'Coordenação','perfil'=>'COORDENADOR'];$_SERVER['REQUEST_URI']='/apc';$response=$controller->index(new Request('GET','/apc',[],[],[]));
        self::assertSame(1,substr_count($response->body,'data-apc-file-group data-professor-name='));self::assertSame(3,substr_count($response->body,'data-apc-file-card'));self::assertStringContainsString('data-apc-file-group-count>3 arquivos',$response->body);self::assertStringContainsString('apc-7a.pdf',$response->body);self::assertStringContainsString('apc-7b.pdf',$response->body);self::assertStringContainsString('apc-7c.pdf',$response->body);self::assertStringContainsString('/apc/envios/1/visualizar',$response->body);self::assertStringContainsString('/apc/envios/2/arquivo',$response->body);self::assertStringContainsString('/apc/envios/3/excluir',$response->body);
    }

    public function testCoordinationSeesCompletePartialAndPendingTeachersFromCouncilBindings():void
    {
        $main=$this->mainDatabase();$this->seedMain($main);$hash=password_hash('interno',PASSWORD_DEFAULT);$statement=$main->prepare("INSERT INTO usuarios(id,nome,email,cpf,senha_hash,perfil)VALUES(5,'Professor Três','p3@test','39053344705',?,'PROFESSOR'),(6,'Professor Sem Série','p4@test','15350946056',?,'PROFESSOR')");$statement->execute([$hash,$hash]);$main->exec("INSERT INTO professores(id,usuario_id)VALUES(3,5),(4,6);INSERT INTO vinculos_professor_turma(id,professor_id,turma_externa_id,turma_nome_snapshot,turma_ano_letivo_snapshot,turno)VALUES(3,1,30,'8º B',2026,'MATUTINO'),(4,3,40,'9º A',2026,'MATUTINO')");
        $apc=$this->apcDatabase();$this->seedEvent($apc);$apc->exec("INSERT INTO apc_envios(id,evento_id,bimestre_id,professor_usuario_id,professor_nome_snapshot,etapa,ano_serie,nome_original,nome_armazenado,mime_type,tamanho_bytes,sha256,caminho_relativo,atrasado,dias_atraso,enviado_em)VALUES(1,1,3,3,'Professor Um','EF_AF','EF7','apc-7.pdf','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf','application/pdf',1200,'".str_repeat('b',64)."','envios/2026/08/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf',1,5,'2026-08-20 10:00:00'),(2,1,3,4,'Professor Dois','EF_AF','EF8','apc-8.pdf','cccccccccccccccccccccccccccccccc.pdf','application/pdf',1300,'".str_repeat('d',64)."','envios/2026/08/cccccccccccccccccccccccccccccccc.pdf',1,5,'2026-08-20 10:05:00');INSERT INTO apc_envio_turmas(envio_id,turma_id_externo,turma_nome_snapshot)VALUES(1,10,'7º A'),(2,20,'8º A')");
        $repository=new SubmissionRepository($apc);$access=new AccessRepository($main);$controller=new SubmissionController(new SubmissionService($repository,new EventRepository($apc),new TermRepository($apc),$access,new AuditRepository($apc),sys_get_temp_dir(),1048576,null,null,'2026-08-20'),$repository,$access,new View(dirname(__DIR__).'/apps/apc/resources/views'));$_SESSION['user']=['id'=>2,'nome'=>'Coordenação','perfil'=>'COORDENADOR'];$_SERVER['REQUEST_URI']='/apc';$response=$controller->index(new Request('GET','/apc',[],[],[]));
        self::assertStringContainsString('Acompanhar pendências',$response->body);self::assertStringContainsString('Consultar arquivos',$response->body);self::assertStringContainsString('Pendências dos professores',$response->body);self::assertStringContainsString('1 de 3 professores concluíram',$response->body);self::assertStringContainsString('Professor Um',$response->body);self::assertStringContainsString('Envio parcial',$response->body);self::assertStringContainsString('8º ano',$response->body);self::assertStringContainsString('Professor Dois',$response->body);self::assertStringContainsString('Enviou tudo',$response->body);self::assertStringContainsString('Professor Três',$response->body);self::assertStringContainsString('Ainda não enviou',$response->body);self::assertStringContainsString('9º ano',$response->body);self::assertStringContainsString('Professor Sem Série',$response->body);self::assertStringContainsString('Vínculos que precisam de conferência',$response->body);self::assertStringContainsString('data-apc-file-search',$response->body);self::assertStringContainsString('data-apc-file-event',$response->body);self::assertStringContainsString('/apc/envios/1/excluir',$response->body);self::assertStringContainsString('>Excluir<',$response->body);
    }

    public function testCoordinatorWhoAlsoTeachesGetsOwnSubmissionAreaAndSchoolManagement():void
    {
        $main=$this->mainDatabase();$this->seedMain($main);$main->exec("INSERT INTO professores(id,usuario_id)VALUES(3,2);INSERT INTO vinculos_professor_turma(id,professor_id,turma_externa_id,turma_nome_snapshot,turma_ano_letivo_snapshot,turno)VALUES(3,3,30,'9º A',2026,'MATUTINO')");
        $apc=$this->apcDatabase();$this->seedEvent($apc);$apc->exec("INSERT INTO apc_envios(id,evento_id,bimestre_id,professor_usuario_id,professor_nome_snapshot,etapa,ano_serie,turma_id_externo,nome_original,nome_armazenado,mime_type,tamanho_bytes,sha256,caminho_relativo,atrasado,dias_atraso,enviado_em)VALUES(1,1,3,3,'Professor Um','EF_AF','EF7',10,'arquivo-professor.pdf','aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf','application/pdf',1200,'".str_repeat('a',64)."','envios/2026/08/aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.pdf',0,0,'2026-08-11 10:00:00');INSERT INTO apc_envio_turmas(envio_id,turma_id_externo,turma_nome_snapshot)VALUES(1,10,'7º A')");
        $repository=new SubmissionRepository($apc);$access=new AccessRepository($main);$controller=new SubmissionController(new SubmissionService($repository,new EventRepository($apc),new TermRepository($apc),$access,new AuditRepository($apc),sys_get_temp_dir(),1048576,null,null,'2026-08-11'),$repository,$access,new View(dirname(__DIR__).'/apps/apc/resources/views'));$_SESSION['user']=['id'=>2,'nome'=>'Coordenação','perfil'=>'COORDENADOR'];$_SERVER['REQUEST_URI']='/apc';$response=$controller->index(new Request('GET','/apc',[],[],[]));
        self::assertStringContainsString('Professor e coordenação',$response->body);self::assertStringContainsString('Minhas APCs e APCs da escola',$response->body);self::assertStringContainsString('data-apc-view-tab="mine"',$response->body);self::assertStringContainsString('data-apc-view-panel="mine"',$response->body);self::assertStringContainsString('data-apc-submission',$response->body);self::assertStringContainsString('9º A',$response->body);self::assertStringContainsString('data-apc-view-panel="tracking"',$response->body);self::assertStringContainsString('<strong>Coordenação</strong>',$response->body);self::assertStringContainsString('data-apc-view-panel="files"',$response->body);self::assertStringContainsString('arquivo-professor.pdf',$response->body);self::assertStringContainsString('/apc/envios/1/excluir',$response->body);
    }
}
