<?php
use PreConselho\Support\Csrf;
$types=['JORNADA_FORMATIVA'=>'Jornada formativa','CONSELHO_CLASSE'=>'Conselho de classe','EMENDA_FERIADO'=>'Emenda de feriado','EXCEPCIONAL'=>'Excepcional','OUTRO'=>'Outro'];
$csrf=Csrf::token();ob_start();
?>
<section class="page-heading"><div><p class="eyebrow">Administração</p><h1>Configurações do APC</h1><p>Gerencie calendário, escala de notas e consulte ações auditadas sem misturar os formulários do Conselho.</p></div></section>
<nav class="admin-nav" aria-label="Seções administrativas"><a href="#calendario">Calendário</a><a href="#parametros">Parâmetros</a><a href="#auditoria">Auditoria</a></nav>

<section class="card admin-section" id="calendario"><div class="section-heading"><div><p class="eyebrow">Calendário APC</p><h2>Novo evento</h2></div></div>
<form method="post" action="/apc/admin/eventos"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><div class="grid"><label>Ano letivo <input type="number" name="ano_letivo" min="2000" max="2100" value="<?=e(date('Y'))?>" required></label><label>Data <input type="date" name="data" required></label><label>Título <input name="titulo" maxlength="160" required></label><label>Tipo <select name="tipo" required><?php foreach($types as$value=>$label):?><option value="<?=e($value)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Origem <select name="origem"><option value="ESCOLA">Escola</option><option value="SED">SED</option></select></label><label>Status <select name="status"><option value="ATIVO">Ativo</option><option value="CANCELADO">Cancelado</option></select></label></div><label>Descrição <textarea name="descricao" maxlength="4000"></textarea></label><div class="grid"><label>Justificativa excepcional <textarea name="justificativa" maxlength="2000"></textarea></label><label>Número do processo <input name="numero_processo" maxlength="120"></label><label>Documento de referência <input name="documento_referencia" maxlength="255"></label><label class="checkbox-label"><input type="checkbox" name="atividade_fornecida_sed" value="1"> Atividade fornecida pela SED</label></div><div class="actions"><button class="primary">Criar evento</button></div></form>
</section>

<section class="card"><div class="section-heading"><div><h2>Eventos cadastrados</h2><p>O cancelamento preserva planos e histórico.</p></div><form method="get" action="/apc/admin"><label>Ano <input type="number" name="ano" min="2000" max="2100" value="<?=e($year===false?'':$year)?>"></label><button>Filtrar</button></form></div>
<?php if(!$events):?><div class="empty-state compact"><p>Nenhum evento cadastrado.</p></div><?php else:?><div class="apc-admin-events"><?php foreach($events as$event):?><details><summary><span><strong><?=e(date('d/m/Y',strtotime($event['data'])).' · '.$event['titulo'])?></strong><small><?=e($types[$event['tipo']]??$event['tipo'])?> · <?=e($event['origem'])?></small></span><span class="badge status-<?=e($event['status']==='ATIVO'?'aprovado':'pendente')?>"><?=e($event['status']==='ATIVO'?'Ativo':'Cancelado')?></span></summary><form method="post" action="/apc/admin/eventos/<?=e($event['id'])?>"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><div class="grid"><label>Ano letivo <input type="number" name="ano_letivo" min="2000" max="2100" value="<?=e($event['ano_letivo'])?>" required></label><label>Data <input type="date" name="data" value="<?=e($event['data'])?>" required></label><label>Título <input name="titulo" maxlength="160" value="<?=e($event['titulo'])?>" required></label><label>Tipo <select name="tipo"><?php foreach($types as$value=>$label):?><option value="<?=e($value)?>" <?=$event['tipo']===$value?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label><label>Origem <select name="origem"><option value="ESCOLA" <?=$event['origem']==='ESCOLA'?'selected':''?>>Escola</option><option value="SED" <?=$event['origem']==='SED'?'selected':''?>>SED</option></select></label><label>Status <select name="status"><option value="ATIVO" <?=$event['status']==='ATIVO'?'selected':''?>>Ativo</option><option value="CANCELADO" <?=$event['status']==='CANCELADO'?'selected':''?>>Cancelado</option></select></label></div><label>Descrição <textarea name="descricao" maxlength="4000"><?=e($event['descricao'])?></textarea></label><div class="grid"><label>Justificativa <textarea name="justificativa" maxlength="2000"><?=e($event['justificativa'])?></textarea></label><label>Número do processo <input name="numero_processo" maxlength="120" value="<?=e($event['numero_processo'])?>"></label><label>Documento de referência <input name="documento_referencia" maxlength="255" value="<?=e($event['documento_referencia'])?>"></label><label class="checkbox-label"><input type="checkbox" name="atividade_fornecida_sed" value="1" <?=$event['atividade_fornecida_sed']?'checked':''?>> Atividade fornecida pela SED</label></div><div class="actions"><button class="primary">Salvar alterações</button></div></form><?php if($event['status']==='ATIVO'):?><form method="post" action="/apc/admin/eventos/<?=e($event['id'])?>/cancelar"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><button class="danger" data-confirm="Cancelar este evento sem apagar o histórico?">Cancelar evento</button></form><?php endif;?></details><?php endforeach;?></div><?php endif;?>
</section>

<section class="card admin-section" id="parametros"><h2>Parâmetros de nota</h2><p class="helper">A escala é exclusiva do APC e não altera as notas do Conselho.</p><form method="post" action="/apc/admin/parametros"><input type="hidden" name="_csrf" value="<?=e($csrf)?>"><div class="grid"><label>Nota mínima <input name="nota_min" inputmode="decimal" value="<?=e($settings['nota_min'])?>" required></label><label>Nota máxima <input name="nota_max" inputmode="decimal" value="<?=e($settings['nota_max'])?>" required></label><label>Casas decimais <input type="number" name="nota_decimais" min="0" max="4" value="<?=e($settings['nota_decimais'])?>" required></label></div><button class="primary">Salvar parâmetros</button></form></section>

<section class="card admin-section" id="auditoria"><h2>Auditoria APC</h2><div class="table"><table><thead><tr><th>Data</th><th>Usuário</th><th>Ação</th><th>Entidade</th><th>ID</th></tr></thead><tbody><?php foreach($audit as$row):?><tr><td><?=e(date('d/m/Y H:i',strtotime($row['criado_em'])))?></td><td><?=e($row['usuario_id']??'Sistema')?></td><td><?=e($row['acao'])?></td><td><?=e($row['entidade'])?></td><td><?=e($row['entidade_id']??'—')?></td></tr><?php endforeach;?></tbody></table></div></section>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
