<?php
$months=[1=>'Janeiro',2=>'Fevereiro',3=>'Março',4=>'Abril',5=>'Maio',6=>'Junho',7=>'Julho',8=>'Agosto',9=>'Setembro',10=>'Outubro',11=>'Novembro',12=>'Dezembro'];$weekdays=['Dom','Seg','Ter','Qua','Qui','Sex','Sáb'];$windowLabels=['ABERTO'=>'Bimestre aberto','AGUARDANDO_BIMESTRE'=>'Bimestre futuro','ENCERRADO'=>'Bimestre encerrado','SEM_BIMESTRE'=>'Prazo não configurado'];$first=new DateTimeImmutable(sprintf('%04d-%02d-01',$year,$month));$start=$first->modify('-'.$first->format('w').' days');$previous=$first->modify('-1 month');$next=$first->modify('+1 month');$byDate=[];foreach($events as$event)$byDate[$event['data']][]=$event;
ob_start();
?>
<nav class="breadcrumbs" aria-label="Navegação estrutural"><a href="/apc">APCs</a> <span aria-hidden="true">›</span> Calendário</nav>
<section class="page-heading"><div><p class="eyebrow">Agenda APC</p><h1><?=e($months[$month].' de '.$year)?></h1><p>Eventos ativos cadastrados pela escola, em uma única agenda.</p></div></section>
<section class="card"><div class="apc-calendar-toolbar"><form method="get" action="/apc/calendario"><label>Ano letivo <select name="ano"><?php foreach($years as$item):?><option value="<?=e($item)?>" <?=$item===$year?'selected':''?>><?=e($item)?></option><?php endforeach;?></select></label><input type="hidden" name="mes" value="<?=e($month)?>"><button>Ir</button></form><nav class="apc-calendar-nav" aria-label="Navegação por mês"><a class="button" href="/apc/calendario?ano=<?=e($previous->format('Y'))?>&amp;mes=<?=e($previous->format('n'))?>">← Mês anterior</a><a class="button" href="/apc/calendario">Hoje</a><a class="button" href="/apc/calendario?ano=<?=e($next->format('Y'))?>&amp;mes=<?=e($next->format('n'))?>">Próximo mês →</a></nav></div></section>
<section class="card"><div class="apc-calendar-grid" aria-label="Calendário mensal"><?php foreach($weekdays as$day):?><div class="calendar-weekday"><?=e($day)?></div><?php endforeach;?><?php for($index=0;$index<42;$index++):$date=$start->modify("+$index days");$dateKey=$date->format('Y-m-d');$outside=$date->format('n')!=$month;$today=$dateKey===$now->format('Y-m-d');?><div class="calendar-day<?=$outside?' outside':''?><?=$today?' today':''?>"><time datetime="<?=e($dateKey)?>"><?=e($date->format('j'))?></time><?php if(isset($byDate[$dateKey])):?><div class="calendar-events"><?php foreach($byDate[$dateKey]as$event):?><a class="calendar-event" href="/apc/eventos/<?=e($event['id'])?>"><?=e($event['titulo'])?><small><?=e($windowLabels[$event['window']['state']])?></small></a><?php endforeach;?></div><?php endif;?></div><?php endfor;?></div>
<div class="calendar-mobile-list" aria-label="Eventos do mês em lista"><?php foreach($events as$event):?><article><span class="badge status-<?=$event['window']['state']==='ABERTO'?'aprovado':'pendente'?>"><?=e($windowLabels[$event['window']['state']])?></span><time datetime="<?=e($event['data'])?>"><strong><?=e(date('d/m/Y',strtotime($event['data'])))?></strong></time><h3><?=e($event['titulo'])?></h3><p><?=e($event['descricao'])?></p><?php if($event['window']['term']):?><small>Envio durante o <?=e($event['window']['term']['numero'])?>º bimestre: <?=e(date('d/m/Y',strtotime($event['window']['opens_on'])))?> a <?=e(date('d/m/Y',strtotime($event['window']['closes_on'])))?></small><?php endif;?><a class="button small-button" href="/apc/eventos/<?=e($event['id'])?>">Ver evento</a></article><?php endforeach;?><?php if(!$events):?><p>Nenhum evento ativo neste mês.</p><?php endif;?></div></section>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
