<?php
use PreConselho\Support\Csrf;
$types=['JORNADA_FORMATIVA'=>'Jornada formativa','CONSELHO_CLASSE'=>'Conselho de classe','EMENDA_FERIADO'=>'Emenda de feriado','EXCEPCIONAL'=>'Excepcional'];$typeCounts=$analysis['counts'];ob_start();
?>
<nav class="breadcrumbs"><a href="/apc/admin#calendario">Administração APC</a> / Conferir calendário</nav>
<section class="page-heading"><div><p class="eyebrow">Importação assistida</p><h1>Conferir calendário de <?=e($analysis['year'])?></h1><p>Nenhum evento foi cadastrado ainda. Revise as datas extraídas do PDF antes de confirmar.</p></div><a class="button" href="/apc/admin#calendario">Cancelar</a></section>

<div class="metrics apc-calendar-metrics" aria-label="Resumo da extração"><article class="metric static status-card-enviado"><span class="metric-label">Ano identificado</span><strong><?=e($analysis['year'])?></strong><small><?=e($analysis['page_count'])?> página(s)</small></article><article class="metric static status-card-aprovado"><span class="metric-label">APCs encontradas</span><strong><?=e(count($analysis['events']))?></strong><small>Datas para revisão</small></article><article class="metric static"><span class="metric-label">Total declarado</span><strong><?=e($analysis['declared_total']??'—')?></strong><small>Informado no PDF</small></article><article class="metric static <?=$analysis['verified']?'status-card-aprovado':'status-card-devolvido'?>"><span class="metric-label">Conferência automática</span><strong><?=$analysis['verified']?'OK':'Revisar'?></strong><small><?=$analysis['verified']?'Totais compatíveis':'Há divergências'?></small></article></div>

<?php if($analysis['verified']):?><div class="flash"><span aria-hidden="true">✓</span><div><strong>Extração conferida com o resumo do calendário.</strong><p><?=e($typeCounts['JORNADA_FORMATIVA']??0)?> jornada(s) formativa(s), <?=e($typeCounts['EMENDA_FERIADO']??0)?> emenda(s) e <?=e($typeCounts['CONSELHO_CLASSE']??0)?> conselho(s) de classe.</p></div></div><?php else:?><div class="error" role="alert"><strong>A extração precisa de atenção.</strong><div><?php foreach($analysis['warnings']as$warning):?><p><?=e($warning)?></p><?php endforeach;?></div></div><?php endif;?>

<section class="card apc-calendar-review" data-calendar-import-review><div class="section-heading"><div><p class="eyebrow">Datas reconhecidas</p><h2>Selecione e confira cada APC</h2><p>Você pode corrigir a data, o tipo e o título. Desmarque uma linha que não deva ser importada.</p></div></div>
<form method="post" action="/apc/admin/calendario/confirmar"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="token" value="<?=e($token)?>"><div class="apc-calendar-extracted-list">
<?php foreach($analysis['events']as$index=>$event):?><article class="apc-calendar-extracted"><label class="apc-calendar-include"><input type="checkbox" name="eventos[<?=e($index)?>][incluir]" value="1" checked> Importar esta data</label><div class="apc-calendar-extracted-fields"><label>Data <input type="date" name="eventos[<?=e($index)?>][data]" value="<?=e($event['data'])?>" min="<?=e($analysis['year'])?>-01-01" max="<?=e($analysis['year'])?>-12-31" required></label><label>Tipo <select name="eventos[<?=e($index)?>][tipo]" required><?php foreach($types as$value=>$label):?><option value="<?=e($value)?>" <?=$event['tipo']===$value?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label><label class="apc-calendar-title">Título <input name="eventos[<?=e($index)?>][titulo]" value="<?=e($event['titulo'])?>" maxlength="160" required></label></div><div class="apc-calendar-evidence"><span>Página <?=e($event['fonte_pagina'])?></span><p><?=e($event['evidencia'])?></p></div></article><?php endforeach;?>
</div><div class="subtle-box apc-calendar-source"><strong>Arquivo analisado</strong><p class="helper"><?=e($analysis['file_name'])?><?php if($analysis['process_number']):?> · Processo <?=e($analysis['process_number'])?><?php endif;?></p></div><label class="checkbox-label apc-calendar-confirm"><input type="checkbox" name="revisado" value="1" required> Revisei as datas acima e confirmo que correspondem às APCs do calendário oficial.</label><div class="actions"><a class="button" href="/apc/admin#calendario">Cancelar</a><button class="primary">Confirmar e importar calendário</button></div></form></section>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
