<?php
use PreConselho\Support\Csrf;
$user=$_SESSION['user'];$editable=$plan['status']==='RASCUNHO'&&$window['is_open']&&$user['perfil']==='PROFESSOR';$decimals=(int)$settings['nota_decimais'];$step=$decimals===0?'1':'0.'.str_repeat('0',max(0,$decimals-1)).'1';
ob_start();
?>
<nav class="breadcrumbs" aria-label="Navegação estrutural"><a href="/apc">APCs</a> <span aria-hidden="true">›</span> <a href="/apc/planos/<?=e($plan['id'])?>">Plano</a> <span aria-hidden="true">›</span> Entregas</nav>
<section class="page-heading"><div><p class="eyebrow">APC — <?=e(date('d/m/Y',strtotime($plan['evento_data'])))?></p><h1>Entregas dos alunos</h1><p><?=e($plan['turma_nome_snapshot'])?> · <?=e($plan['componente_curricular'])?> · <?=e($plan['professor_nome_snapshot'])?></p></div><span class="badge status-<?=e(strtolower($plan['status']))?>"><?=e($plan['status']==='FINALIZADO'?'Finalizado':'Rascunho')?></span></section>
<nav class="apc-tabs" aria-label="Seções do plano"><a href="/apc/planos/<?=e($plan['id'])?>">Plano de Ação</a><a class="active" href="/apc/planos/<?=e($plan['id'])?>/entregas">Entregas dos alunos</a></nav>
<div class="subtle-box"><strong>Janela da APC: <?=e(date('d/m/Y',strtotime($window['opens_on'])))?> a <?=e(date('d/m/Y',strtotime($window['closes_on'])))?></strong><p class="helper"><?php if($window['is_open']):?>O registro de entregas e anexos está disponível automaticamente.<?php else:?>O período está fechado; entregas e anexos permanecem disponíveis somente para consulta.<?php endif;?></p></div>
<?php if($error):?><div class="error" role="alert"><?=e($error)?></div><?php endif;?>
<?php if(!$editable&&$user['perfil']==='PROFESSOR'&&$plan['status']==='FINALIZADO'):?><div class="subtle-box">O plano está finalizado. Entregas e anexos ficam disponíveis apenas para consulta.</div><?php endif;?>
<section class="apc-student-list" aria-label="Estudantes da turma">
<?php if(!$students):?><div class="card empty-state"><h2>Nenhum aluno disponível</h2><p>A lista da Secretaria API não pôde ser carregada e ainda não há snapshots de entregas.</p></div><?php endif;?>
<?php foreach($students as$student):$delivery=$student['entrega'];$delivered=(bool)($delivery['entregue']??false);?>
<article class="card apc-student-card" id="aluno-<?=e($student['id'])?>">
    <header><div><h2><?=e($student['nome'])?></h2><?php if($student['fora_lista_atual']):?><small>Registro histórico; aluno não localizado na lista atual da turma.</small><?php endif;?></div><span class="badge status-<?=$delivered?'aprovado':'pendente'?>"><?=$delivered?'Realizada':'Não realizada'?></span></header>
    <?php if($editable):?><form method="post" action="/apc/planos/<?=e($plan['id'])?>/entregas/<?=e($student['id'])?>"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><div class="apc-delivery-grid"><label class="checkbox-label"><input type="checkbox" name="entregue" value="1" <?=$delivered?'checked':''?>> Entregou</label><label>Data da entrega <input type="date" name="data_entrega" value="<?=e($delivery['data_entrega']??'')?>"></label><label>Nota <input inputmode="decimal" name="nota" min="<?=e($settings['nota_min'])?>" max="<?=e($settings['nota_max'])?>" step="<?=e($step)?>" value="<?=e($delivery['nota']??'')?>"><small class="helper">Escala: <?=e($settings['nota_min'])?> a <?=e($settings['nota_max'])?></small></label><label class="delivery-observation">Observação <textarea name="observacao" maxlength="4000"><?=e($delivery['observacao']??'')?></textarea></label></div><div class="actions"><button class="primary">Salvar entrega</button></div></form>
    <?php else:?><dl class="identity delivery-summary"><div><dt>Entregou?</dt><dd><?=$delivered?'Sim':'Não'?></dd></div><div><dt>Data</dt><dd><?=!empty($delivery['data_entrega'])?e(date('d/m/Y',strtotime($delivery['data_entrega']))):'—'?></dd></div><div><dt>Nota</dt><dd><?=isset($delivery['nota'])&&$delivery['nota']!==null?e($delivery['nota']):'—'?></dd></div></dl><?php if(!empty($delivery['observacao'])):?><p><strong>Observação:</strong> <?=nl2br(e($delivery['observacao']))?></p><?php endif;?><?php endif;?>
    <section class="apc-attachments" aria-label="Anexos de <?=e($student['nome'])?>"><h3>Anexos <span class="badge"><?=count($student['anexos'])?></span></h3><?php if($student['anexos']):?><ul><?php foreach($student['anexos']as$file):?><li><a href="/apc/anexos/<?=e($file['id'])?>"><?=e($file['nome_original'])?></a> <small><?=e(number_format((int)$file['tamanho_bytes']/1024,1,',','.'))?> KB</small><?php if($editable):?><form method="post" action="/apc/anexos/<?=e($file['id'])?>/excluir"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><button class="danger small-button" data-confirm="Remover este anexo de forma permanente?">Remover</button></form><?php endif;?></li><?php endforeach;?></ul><?php else:?><p class="helper">Nenhuma comprovação anexada.</p><?php endif;?>
    <?php if($editable&&$delivery):?><form method="post" action="/apc/entregas/<?=e($delivery['id'])?>/anexos" enctype="multipart/form-data" data-apc-upload-form><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><label>Adicionar comprovações <input type="file" name="arquivos[]" accept="application/pdf,image/jpeg,image/png,image/webp" multiple required></label><small class="helper">PDF, JPEG, PNG ou WebP. Os arquivos ficam fora da área pública.</small><button class="button">Enviar anexo(s)</button></form><?php elseif($editable):?><p class="helper">Salve o registro da entrega antes de adicionar anexos.</p><?php endif;?></section>
</article>
<?php endforeach;?>
</section>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
