<?php
use PreConselho\Support\Csrf;
$user=$_SESSION['user'];$editing=$plan!==null;$editable=!$editing||$plan['status']==='RASCUNHO';$isTeacher=$user['perfil']==='PROFESSOR';$canEdit=$editable&&$isTeacher;$event=$editing?$plan:$selectedEvent;
$stageLabels=['EF_AI'=>'Ensino Fundamental — Anos Iniciais','EF_AF'=>'Ensino Fundamental — Anos Finais','EM'=>'Ensino Médio'];$yearLabels=['EF1'=>'1º ano','EF2'=>'2º ano','EF3'=>'3º ano','EF4'=>'4º ano','EF5'=>'5º ano','EF6'=>'6º ano','EF7'=>'7º ano','EF8'=>'8º ano','EF9'=>'9º ano','EM1'=>'1ª série do Ensino Médio','EM2'=>'2ª série do Ensino Médio','EM3'=>'3ª série do Ensino Médio'];
$selectedComponents=array_fill_keys(array_map('intval',array_column($planCurriculum['componentes']??[],'componente_id')),true);$selectedAbilities=$planCurriculum['habilidades']??[];$hasStructured=(bool)$selectedComponents;$legacy=$editing&&!$hasStructured;$selectedStage=$editing?(string)($plan['etapa']??''):'';$selectedYear=$editing?(string)($plan['ano_serie']??''):'';
ob_start();
?>
<nav class="breadcrumbs" aria-label="Navegação estrutural"><a href="/apc">APCs</a> <span aria-hidden="true">›</span> <?=$editing?'Plano de Ação':'Novo plano'?></nav>
<section class="page-heading"><div><p class="eyebrow">Plano de Ação</p><h1><?=$editing?'APC — '.e(date('d/m/Y',strtotime($plan['evento_data']))):'Novo Plano APC'?></h1><?php if($editing):?><p>Turma: <strong><?=e($plan['turma_nome_snapshot'])?></strong> · Professor: <strong><?=e($plan['professor_nome_snapshot'])?></strong></p><?php else:?><p>Associe o planejamento a um evento e a uma turma em que você leciona.</p><?php endif;?></div><?php if($editing):?><span class="badge status-<?=e(strtolower($plan['status']))?>"><?=e($plan['status']==='FINALIZADO'?'Finalizado':'Rascunho')?></span><?php endif;?></section>

<?php if($editing):?><nav class="apc-tabs" aria-label="Seções do plano"><a class="active" href="/apc/planos/<?=e($plan['id'])?>">Plano de Ação</a><a href="/apc/planos/<?=e($plan['id'])?>/entregas">Entregas dos alunos</a></nav><?php endif;?>

<section class="card">
<form method="post" action="<?=$editing?'/apc/planos/'.e($plan['id']):'/apc/planos'?>" data-curriculum-plan>
    <input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>">
    <?php if(!$editing):?>
    <div class="grid"><label>Evento APC <select name="evento_id" required><option value="">Selecione</option><?php foreach($events as$item):?><option value="<?=e($item['id'])?>" <?=($selectedEvent&&$selectedEvent['id']===$item['id'])?'selected':''?>><?=e(date('d/m/Y',strtotime($item['data'])).' · '.$item['titulo'])?></option><?php endforeach;?></select></label><label>Turma <select name="turma_id_externo" required><option value="">Selecione</option><?php foreach($classes as$class):?><option value="<?=e($class['id'])?>"><?=e($class['nome'])?></option><?php endforeach;?></select></label></div>
    <?php else:?><dl class="identity"><div><dt>Evento</dt><dd><?=e($plan['evento_titulo'])?></dd></div><div><dt>Data da APC</dt><dd><?=e(date('d/m/Y',strtotime($plan['evento_data'])))?></dd></div><div><dt>Origem</dt><dd><?=e($plan['evento_origem'])?></dd></div></dl><?php endif;?>

    <fieldset class="curriculum-section"><legend>Informações curriculares</legend>
    <?php if($legacy):?>
        <p class="subtle-box"><strong>Informação curricular registrada anteriormente.</strong> Este plano permanece no formato textual legado. Ele pode continuar sendo editado e consultado sem perda de dados.</p>
        <label>Componente curricular <input name="componente_curricular" maxlength="160" required value="<?=e($plan['componente_curricular'])?>" <?=$canEdit?'':'readonly'?>></label>
    <?php elseif(!$components):?>
        <p class="subtle-box">O catálogo curricular ainda não foi importado. Peça à administração para executar a importação antes de criar novos planos estruturados.</p>
    <?php else:?>
        <div class="grid"><label>Etapa <select name="etapa" data-curriculum-stage required <?=$canEdit?'':'disabled'?>> <option value="">Selecione</option><?php foreach($stageLabels as$value=>$label):?><option value="<?=e($value)?>" <?=$selectedStage===$value?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label><label>Ano/Série <select name="ano_serie" data-curriculum-year required <?=$canEdit?'':'disabled'?>> <option value="">Selecione</option><?php foreach($yearLabels as$value=>$label):$stage=str_starts_with($value,'EM')?'EM':((int)substr($value,2)<=5?'EF_AI':'EF_AF');?><option value="<?=e($value)?>" data-stage="<?=e($stage)?>" <?=$selectedYear===$value?'selected':''?>><?=e($label)?></option><?php endforeach;?></select></label></div>
        <?php if(!$canEdit):?><input type="hidden" name="etapa" value="<?=e($selectedStage)?>"><input type="hidden" name="ano_serie" value="<?=e($selectedYear)?>"><?php endif;?>
        <div class="curriculum-components"><div class="section-heading"><div><h3>Componentes curriculares</h3><p>Selecione um ou mais componentes para um plano interdisciplinar.</p></div></div><div class="curriculum-choice-grid" data-curriculum-components><?php foreach($components as$component):$selected=isset($selectedComponents[(int)$component['id']]);if(!$component['ativo']&&!$selected)continue;?><label data-stage="<?=e($component['etapa'])?>" class="curriculum-choice <?=$component['modalidade']==='EDUCACAO_DO_CAMPO'?'field-component':''?>"><input type="checkbox" name="componentes[]" value="<?=e($component['id'])?>" data-component-name="<?=e($component['nome'])?>" <?=$selected?'checked':''?> <?=$canEdit?'':'disabled'?>> <span><strong><?=e($component['sigla'])?></strong> <?=e($component['nome'])?><?php if(!$component['ativo']):?><small>Histórico — inativo</small><?php elseif($component['modalidade']==='EDUCACAO_DO_CAMPO'):?><small>Educação do Campo</small><?php endif;?></span></label><?php endforeach;?></div></div>
        <?php if(!$canEdit):?><?php foreach(array_keys($selectedComponents)as$id):?><input type="hidden" name="componentes[]" value="<?=e($id)?>"><?php endforeach;?><?php endif;?>
        <div class="selected-abilities"><div class="section-heading"><div><h3>Habilidades selecionadas</h3><p>As descrições e os códigos ficam preservados no histórico do plano.</p></div></div><div data-selected-abilities><?php foreach($selectedAbilities as$ability):?><article class="selected-ability" data-ability-id="<?=e($ability['habilidade_id'])?>" data-component-id="<?=e($ability['componente_id'])?>"><input type="hidden" name="habilidades[]" value="<?=e($ability['habilidade_id'])?>"><div><span class="badge"><?=e($ability['componente_nome_snapshot'])?></span><strong><?=e($ability['habilidade_codigo_snapshot']?:'Sem código')?></strong><p><?=e($ability['habilidade_descricao_snapshot'])?></p></div><?php if($canEdit):?><button type="button" class="button small-button" data-remove-ability>Remover</button><?php endif;?></article><?php endforeach;?></div><?php if(!$selectedAbilities):?><p class="helper" data-no-abilities>Nenhuma habilidade selecionada. É possível salvar o rascunho e completar depois.</p><?php endif;?></div>
        <?php if($canEdit):?><div class="curriculum-search" data-curriculum-search><h3>Buscar/adicionar habilidade</h3><div class="grid"><label>Componente selecionado <select data-ability-component><option value="">Selecione um componente acima</option></select></label><label>Buscar por código ou texto <input type="search" maxlength="120" data-ability-query placeholder="Ex.: solo, MS.EF08..."></label></div><button type="button" class="button" data-search-abilities>Buscar habilidades</button><p class="helper" role="status" data-ability-status>Use etapa, ano/série e componente para filtrar o catálogo local.</p><div class="ability-results" data-ability-results></div></div><?php endif;?>
    <?php endif;?>
    <label>Complemento / observação curricular <textarea name="competencias_habilidades" maxlength="12000" <?=$canEdit?'':'readonly'?>><?=e($editing?$plan['competencias_habilidades']:'')?></textarea><small class="helper">Use para orientações específicas, projetos interdisciplinares ou habilidades ainda não disponíveis no catálogo.</small></label>
    </fieldset>
    <label>Conteúdos / objetos abordados <textarea name="conteudos" maxlength="12000" aria-required="true" <?=$canEdit?'':'readonly'?>><?=e($editing?$plan['conteudos']:'')?></textarea><small class="helper">Obrigatório para finalizar o plano.</small></label>
    <label>Descrição da atividade planejada <textarea name="descricao_atividade" maxlength="20000" aria-required="true" <?=$canEdit?'':'readonly'?>><?=e($editing?$plan['descricao_atividade']:'')?></textarea><small class="helper">A atividade é elaborada e aplicada fora deste sistema.</small></label>
    <label>Estratégia de devolução dos estudantes <textarea name="estrategia_devolucao" maxlength="12000" aria-required="true" <?=$canEdit?'':'readonly'?>><?=e($editing?$plan['estrategia_devolucao']:'')?></textarea></label>
    <?php if($canEdit):?><div class="actions"><a class="button" href="/apc">Cancelar</a><button class="primary" formnovalidate>Salvar rascunho</button></div><?php endif;?>
</form>
<?php if($editing&&$editable&&$isTeacher):?><form method="post" action="/apc/planos/<?=e($plan['id'])?>/finalizar"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><div class="actions"><a class="button" href="/apc/planos/<?=e($plan['id'])?>/entregas">Registrar entregas</a><button class="primary" data-confirm="Finalizar este plano? As alterações ficarão bloqueadas.">Finalizar plano</button></div></form><?php endif;?>
<?php if($editing&&!$editable):?><p class="subtle-box">Este plano está finalizado e disponível somente para consulta. A coordenação ou administração pode reabri-lo com motivo registrado em auditoria.</p><?php endif;?>
</section>
<?php if($editing&&$plan['status']==='FINALIZADO'&&in_array($user['perfil'],['ADMIN','COORDENADOR'],true)):?><section class="card review-card"><h2>Reabrir plano</h2><form method="post" action="/apc/planos/<?=e($plan['id'])?>/reabrir"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><label>Motivo <textarea name="motivo" required maxlength="1000"></textarea></label><button class="danger" data-confirm="Confirma a reabertura deste plano?">Reabrir com auditoria</button></form></section><?php endif;?>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
