<?php use PreConselho\Support\Csrf;$days=[1=>'SEGUNDA',2=>'TERÇA',3=>'QUARTA',4=>'QUINTA',5=>'SEXTA'];$groups=[];$classLabels=[];$teacherLabels=[];foreach($analysis['rows']as$row){$groups[$row['turma_importada']][$row['dia_semana']][]=$row;$classLabels[$row['turma_key']]=$row['turma_importada'];$teacherLabels[$row['professor_key']]=$row['professor_nome_importado'];}ob_start();?>
<nav class="breadcrumbs" aria-label="Navegação estrutural"><a href="/apc/admin/horarios">Horários</a> <span aria-hidden="true">›</span> Conferência</nav>
<section class="page-heading"><div><p class="eyebrow">Conferência obrigatória</p><h1><?=e($analysis['ano_letivo'].' · '.ucfirst(mb_strtolower($analysis['turno'])))?></h1><p><?=e(date('d/m/Y',strtotime($analysis['vigente_de'])))?> a <?=e($analysis['vigente_ate']?date('d/m/Y',strtotime($analysis['vigente_ate'])):'sem término')?> · <?=e($analysis['counts']['aulas'])?> aula(s)</p></div></section>
<form method="post" action="/apc/admin/horarios/confirmar"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="token" value="<?=e($token)?>">
<?php foreach($analysis['class_matches']as$key=>$match):?><section class="card"><div class="section-heading"><div><h2>Turma importada: <?=e($classLabels[$key]??$key)?></h2></div><span class="badge"><?=e($match['status']==='safe'?'Reconhecida':'Revisão necessária')?></span></div><?php if($match['status']==='safe'):?><p>Associada a <strong><?=e($match['name'])?></strong>.</p><?php else:?><label>Selecionar turma correta <select name="turma_map[<?=e($key)?>]" required><option value="">Selecione</option><?php foreach($analysis['classes']as$class):?><option value="<?=e($class['id'])?>"><?=e($class['nome'])?></option><?php endforeach;?></select></label><?php endif;?></section><?php endforeach;?>
<section class="card"><h2>Professores para revisão</h2><div class="grid"><?php foreach($analysis['teacher_matches']as$key=>$match):?><label><?=e($teacherLabels[$key]??$key)?><?php if($match['status']==='safe'):?><input value="<?=e($match['name'])?>" disabled><small class="helper">Correspondência normalizada segura.</small><?php else:?><select name="professor_map[<?=e($key)?>]" required><option value="">Selecione o usuário correto</option><?php foreach($analysis['teachers']as$teacher):?><option value="<?=e($teacher['id'])?>"><?=e($teacher['nome'])?></option><?php endforeach;?></select><?php if($match['suggestions']):?><small class="helper">Sugestões: <?=e(implode(', ',array_column($match['suggestions'],'nome')))?></small><?php endif;?><?php endif;?></label><?php endforeach;?></div></section>
<?php foreach($groups as$class=>$week):?><section class="card"><h2><?=e($class.' · '.ucfirst(mb_strtolower($analysis['turno'])))?></h2><?php foreach($week as$day=>$rows):?><h3><?=e($days[$day])?></h3><div class="table"><table><thead><tr><th>Aula</th><th>Disciplina</th><th>Professor importado</th><th>Situação</th></tr></thead><tbody><?php foreach($rows as$row):?><tr><td><?=e($row['numero_aula'])?>ª</td><td><?=e($row['disciplina'])?></td><td><?=e($row['professor_nome_importado'])?></td><td><?=e($row['professor_match']['status']==='safe'?'Reconhecido':'Associação manual necessária')?></td></tr><?php endforeach;?></tbody></table></div><?php endforeach;?></section><?php endforeach;?>
<section class="card"><p>A confirmação grava toda a versão em uma única transação. Nenhum registro será criado se alguma associação estiver ausente ou inválida.</p><div class="actions"><a class="button" href="/apc/admin/horarios">Cancelar</a><button class="primary">Confirmar e gravar grade</button></div></section></form>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
