<?php
use PreConselho\Support\Csrf;
$user=$_SESSION['user'];$firstName=explode(' ',trim((string)$user['nome']))[0];$stageLabels=['EF_AI'=>'Ensino Fundamental — Anos Iniciais','EF_AF'=>'Ensino Fundamental — Anos Finais','EM'=>'Ensino Médio'];$yearLabels=['EF1'=>'1º ano','EF2'=>'2º ano','EF3'=>'3º ano','EF4'=>'4º ano','EF5'=>'5º ano','EF6'=>'6º ano','EF7'=>'7º ano','EF8'=>'8º ano','EF9'=>'9º ano','EM1'=>'1ª série','EM2'=>'2ª série','EM3'=>'3ª série'];$stages=[];foreach($series as$item)$stages[$item['etapa']]=$item['rotulo_etapa'];$lateCount=count(array_filter($submissions,static fn(array$item):bool=>(bool)$item['atrasado']));ob_start();
?>
<section class="page-heading"><div><p class="eyebrow"><?=$isTeacher?'Área do professor':'Acompanhamento da coordenação'?></p><h1><?=$isTeacher?'Enviar APC':'Arquivos de APC enviados'?></h1><p><?=$isTeacher?'Olá, '.e($firstName).'. Selecione o evento, a etapa e a série e anexe o modelo já preenchido.':'Consulte os arquivos enviados pelos professores e identifique imediatamente os que chegaram após a data da APC.'?></p></div><?php if($term):?><span class="badge status-aprovado"><?=e($term['numero'])?>º bimestre · <?=e(date('d/m',strtotime($term['data_inicio'])))?> a <?=e(date('d/m',strtotime($term['data_fim'])))?></span><?php endif;?></section>

<?php if($isTeacher):?>
<section class="card apc-simple-upload"><div class="section-heading"><div><p class="eyebrow">Envio simplificado</p><h2>Anexar o modelo pronto</h2><p>As etapas e séries são liberadas conforme as turmas vinculadas ao seu usuário no Conselho de Classe.</p></div></div>
<?php if(!$term):?><div class="empty-state compact"><h3>Fora do calendário letivo</h3><p>Não existe um bimestre aberto para envio na data atual.</p></div><?php elseif(!$series):?><div class="error" role="alert"><strong>Nenhuma etapa ou série disponível.</strong> Solicite à administração que confira seus vínculos de turma no Conselho de Classe.</div><?php elseif(!$events):?><div class="empty-state compact"><h3>Nenhum evento neste bimestre</h3><p>Não há evento APC ativo disponível para envio.</p></div><?php else:?><form method="post" action="/apc/envios" enctype="multipart/form-data" data-apc-submission><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><div class="apc-submission-fields"><label>Evento <select name="evento_id" required><option value="">Selecione o evento</option><?php foreach($events as$event):?><option value="<?=e($event['id'])?>"><?=e(date('d/m/Y',strtotime($event['data'])).' · '.$event['titulo'].($event['submission_window']['is_late']?' — será marcado como atraso':''))?></option><?php endforeach;?></select></label><label>Etapa <select name="etapa" required data-submission-stage><option value="">Selecione a etapa</option><?php foreach($stages as$value=>$label):?><option value="<?=e($value)?>"><?=e($label)?></option><?php endforeach;?></select></label><label>Ano/Série <select name="ano_serie" required data-submission-year disabled><option value="">Selecione a série</option><?php foreach($series as$item):?><option value="<?=e($item['ano_serie'])?>" data-stage="<?=e($item['etapa'])?>" data-classes="<?=e(implode(', ',array_column($item['turmas'],'nome')))?>"><?=e($item['rotulo_serie'])?></option><?php endforeach;?></select><small class="helper" data-submission-classes>Escolha a etapa para visualizar suas séries vinculadas.</small></label><label class="submission-file-field">Arquivo da APC <input type="file" name="arquivo" accept=".pdf,.doc,.docx,.odt,.jpg,.jpeg,.png,.webp,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,application/vnd.oasis.opendocument.text,image/jpeg,image/png,image/webp" required><small class="helper">PDF, Word, ODT ou imagem. Limite configurado pela escola.</small></label></div><div class="subtle-box"><strong>Prazo do <?=e($term['numero'])?>º bimestre: <?=e(date('d/m/Y',strtotime($term['data_inicio'])))?> a <?=e(date('d/m/Y',strtotime($term['data_fim'])))?></strong><p class="helper">O envio continua permitido após a data do evento, mas ficará identificado como <strong>Entregue com atraso</strong>.</p></div><div class="actions"><button class="primary">Anexar arquivo da APC</button></div></form><?php endif;?></section>
<?php else:?><div class="metrics teacher-summary" aria-label="Resumo dos arquivos"><article class="metric static"><span class="metric-label">Arquivos anexados</span><strong><?=count($submissions)?></strong><small>Total recebido</small></article><article class="metric static status-card-aprovado"><span class="metric-label">No prazo</span><strong><?=count($submissions)-$lateCount?></strong><small>Até a data da APC</small></article><article class="metric static status-card-devolvido"><span class="metric-label">Com atraso</span><strong><?=$lateCount?></strong><small>Após a data da APC</small></article></div><?php endif;?>

<section class="card"><div class="section-heading"><div><p class="eyebrow"><?=$isTeacher?'Comprovante de envio':'Acompanhamento'?></p><h2><?=$isTeacher?'Meus arquivos anexados':'Envios dos professores'?></h2><p><?=$isTeacher?'Depois do envio, o arquivo permanece listado aqui com data e situação.':'Os vínculos de turma exibidos são os mesmos cadastrados no Conselho de Classe.'?></p></div></div><?php if(!$submissions):?><div class="empty-state"><span aria-hidden="true">↥</span><h3>Nenhum arquivo anexado</h3><p><?=$isTeacher?'Use o formulário acima para enviar sua primeira APC.':'Os arquivos aparecerão assim que os professores realizarem os envios.'?></p></div><?php else:?><div class="apc-submission-list"><?php foreach($submissions as$item):?><article class="apc-submission-card"><div class="submission-status"><span class="badge status-aprovado">Arquivo anexado</span><?php if($item['atrasado']):?><span class="badge status-devolvido">Entregue com atraso · <?=e($item['dias_atraso'])?> dia(s)</span><?php else:?><span class="badge status-enviado">Entregue no prazo</span><?php endif;?></div><div class="submission-copy"><time datetime="<?=e($item['evento_data'])?>"><?=e(date('d/m/Y',strtotime($item['evento_data'])))?></time><h3><?=e($item['evento_titulo'])?></h3><?php if(!$isTeacher):?><p><strong><?=e($item['professor_nome_snapshot'])?></strong></p><?php endif;?><p><?=e($stageLabels[$item['etapa']]??$item['etapa'])?> · <?=e($yearLabels[$item['ano_serie']]??$item['ano_serie'])?></p><small>Turma(s) vinculada(s): <?=e($item['turmas']?:'Vínculo histórico indisponível')?></small></div><div class="submission-file"><strong><?=e($item['nome_original'])?></strong><small><?=e(number_format((int)$item['tamanho_bytes']/1024,1,',','.'))?> KB · anexado em <?=e(date('d/m/Y H:i',strtotime($item['enviado_em'])))?></small><a class="button" href="/apc/envios/<?=e($item['id'])?>/arquivo">Baixar arquivo</a></div></article><?php endforeach;?></div><?php endif;?></section>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
