<?php
$user=$_SESSION['user'];$isTeacher=$user['perfil']==='PROFESSOR';$stageLabels=['EF_AI'=>'Ensino Fundamental — Anos Iniciais','EF_AF'=>'Ensino Fundamental — Anos Finais','EM'=>'Ensino Médio'];$yearLabels=['EF1'=>'1º ano','EF2'=>'2º ano','EF3'=>'3º ano','EF4'=>'4º ano','EF5'=>'5º ano','EF6'=>'6º ano','EF7'=>'7º ano','EF8'=>'8º ano','EF9'=>'9º ano','EM1'=>'1ª série','EM2'=>'2ª série','EM3'=>'3ª série'];ob_start();
?>
<nav class="breadcrumbs" aria-label="Navegação estrutural"><a href="/apc">APCs</a> <span aria-hidden="true">›</span> Visualizar envio</nav>
<section class="page-heading"><div><p class="eyebrow">APC enviada</p><h1><?=e($submission['nome_original'])?></h1><p><?=e($submission['evento_titulo'])?> · <?=e(date('d/m/Y',strtotime($submission['evento_data'])))?></p></div><a class="button" href="/apc">Voltar para as APCs</a></section>
<section class="card apc-preview-summary"><div><span class="badge status-aprovado">Arquivo anexado</span><?php if($submission['atrasado']):?><span class="badge status-devolvido">Entregue com atraso</span><?php else:?><span class="badge status-enviado">Entregue no prazo</span><?php endif;?></div><dl class="event-detail-grid"><?php if(!$isTeacher):?><div><dt>Professor</dt><dd><?=e($submission['professor_nome_snapshot'])?></dd></div><?php endif;?><div><dt>Etapa e série</dt><dd><?=e($stageLabels[$submission['etapa']]??$submission['etapa'])?> · <?=e($yearLabels[$submission['ano_serie']]??$submission['ano_serie'])?></dd></div><div><dt>Turmas vinculadas</dt><dd><?=e($submission['turmas']?:'Não informadas')?></dd></div><div><dt>Enviado em</dt><dd><?=e(date('d/m/Y H:i',strtotime($submission['enviado_em'])))?></dd></div><div><dt>Tamanho</dt><dd><?=e(number_format((int)$submission['tamanho_bytes']/1024,1,',','.'))?> KB</dd></div></dl></section>
<section class="card apc-preview-card"><div class="section-heading"><div><p class="eyebrow">Visualização</p><h2>Conteúdo da APC</h2><p>O arquivo permanece protegido e somente usuários autorizados conseguem acessá-lo.</p></div><a class="button" href="/apc/envios/<?=e($submission['id'])?>/arquivo">Baixar arquivo</a></div>
<?php if($previewable):?><?php if($isImage):?><div class="apc-image-preview"><img src="/apc/envios/<?=e($submission['id'])?>/conteudo" alt="Conteúdo do arquivo <?=e($submission['nome_original'])?>"></div><?php else:?><iframe class="apc-pdf-preview" src="/apc/envios/<?=e($submission['id'])?>/conteudo" title="Conteúdo do arquivo <?=e($submission['nome_original'])?>"></iframe><?php endif;?><?php else:?><div class="empty-state apc-preview-unavailable"><span aria-hidden="true">DOC</span><h3>Visualização direta indisponível para este formato</h3><p>Arquivos Word e ODT precisam ser abertos em um aplicativo compatível. O download continua protegido pelo sistema.</p><a class="button primary" href="/apc/envios/<?=e($submission['id'])?>/arquivo">Baixar para abrir</a></div><?php endif;?>
</section>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
