<?php
use PreConselho\Support\Csrf;
$user=$_SESSION['user'];$isTeacher=$user['perfil']==='PROFESSOR';$stageLabels=['EF_AI'=>'Ensino Fundamental — Anos Iniciais','EF_AF'=>'Ensino Fundamental — Anos Finais','EM'=>'Ensino Médio'];$yearLabels=['EF1'=>'1º ano','EF2'=>'2º ano','EF3'=>'3º ano','EF4'=>'4º ano','EF5'=>'5º ano','EF6'=>'6º ano','EF7'=>'7º ano','EF8'=>'8º ano','EF9'=>'9º ano','EM1'=>'1ª série','EM2'=>'2ª série','EM3'=>'3ª série'];$extension=mb_strtoupper(pathinfo((string)$submission['nome_original'],PATHINFO_EXTENSION)?:'ARQ');ob_start();
?>
<nav class="breadcrumbs" aria-label="Navegação estrutural"><a href="/apc">APCs</a> <span aria-hidden="true">›</span> Visualizar envio</nav>

<section class="page-heading apc-preview-heading"><div><p class="eyebrow">Visualização do arquivo</p><h1><?=e($submission['evento_titulo'])?></h1><p>APC de <?=e(date('d/m/Y',strtotime($submission['evento_data'])))?></p></div><a class="button" href="/apc<?=$isTeacher?'':'#arquivos'?>">← Voltar aos envios</a></section>

<section class="card apc-preview-overview">
    <div class="apc-preview-identity"><span class="apc-file-type" aria-hidden="true"><?=e($extension)?></span><div><p class="eyebrow"><?=$isTeacher?'Seu arquivo':'Arquivo recebido'?></p><h2><?=e($submission['nome_original'])?></h2><p><?=$isTeacher?'Enviado por você':'Enviado por '.e($submission['professor_nome_snapshot'])?> para <strong><?=e($submission['turmas']?:'turma não informada')?></strong>.</p></div><div class="apc-preview-status"><span class="badge status-aprovado">Anexado</span><?php if($submission['atrasado']):?><span class="badge status-devolvido">Com atraso</span><?php else:?><span class="badge status-enviado">No prazo</span><?php endif;?></div></div>
    <dl class="apc-preview-details"><div><dt>Professor</dt><dd><?=$isTeacher?'Você':e($submission['professor_nome_snapshot'])?></dd></div><div><dt>Turma</dt><dd><?=e($submission['turmas']?:'Não informada')?></dd></div><div><dt>Etapa e série</dt><dd><?=e($stageLabels[$submission['etapa']]??$submission['etapa'])?> · <?=e($yearLabels[$submission['ano_serie']]??$submission['ano_serie'])?></dd></div><div><dt>Data do envio</dt><dd><?=e(date('d/m/Y H:i',strtotime($submission['enviado_em'])))?></dd></div><div><dt>Tamanho</dt><dd><?=e(number_format((int)$submission['tamanho_bytes']/1024,1,',','.'))?> KB</dd></div></dl>
</section>

<section class="card apc-preview-card"><div class="apc-preview-toolbar"><div><p class="eyebrow">Documento</p><h2>Conteúdo da APC</h2></div><div class="submission-file-actions"><a class="button" href="/apc/envios/<?=e($submission['id'])?>/arquivo">Baixar arquivo</a><?php if(!$isTeacher):?><form method="post" action="/apc/envios/<?=e($submission['id'])?>/excluir"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><button class="danger" data-confirm="Excluir definitivamente este envio? A turma voltará a ficar pendente.">Excluir envio</button></form><?php endif;?></div></div>
<?php if($previewable):?><?php if($isImage):?><div class="apc-image-preview"><img src="/apc/envios/<?=e($submission['id'])?>/conteudo" alt="Conteúdo do arquivo <?=e($submission['nome_original'])?>"></div><?php else:?><iframe class="apc-pdf-preview" src="/apc/envios/<?=e($submission['id'])?>/conteudo" title="Conteúdo do arquivo <?=e($submission['nome_original'])?>"></iframe><?php endif;?><?php else:?><div class="empty-state apc-preview-unavailable"><span aria-hidden="true"><?=e($extension)?></span><h3>Este formato não abre diretamente no navegador</h3><p>O arquivo continua protegido. Baixe-o para abrir no Word ou em outro aplicativo compatível.</p><a class="button primary" href="/apc/envios/<?=e($submission['id'])?>/arquivo">Baixar e abrir</a></div><?php endif;?>
</section>
<?php $content=ob_get_clean();require dirname(__DIR__,3).'/preconselho-web/resources/views/layout.php';
