<?php declare(strict_types=1);
use PreConselho\Controllers\{BindingController,ManagementController,WebController};
use PreConselho\Integration\SecretariaApiClient;
use PreConselho\Middlewares\{AuthMiddleware,RoleMiddleware};
use PreConselho\Repositories\AppRepository;
use Shared\Database\ConnectionFactory;
use Shared\Env;
use Shared\Exceptions\HttpException;
use Shared\Http\{Request,Response,Router};
use Shared\Support\View;

$root=dirname(__DIR__,3);require $root.'/vendor/autoload.php';require $root.'/shared/Support/helpers.php';Env::load($root.'/.env');
date_default_timezone_set(Env::get('APP_TIMEZONE','America/Sao_Paulo')??'America/Sao_Paulo');$https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';session_name('preconselho_session');session_set_cookie_params(['httponly'=>true,'secure'=>$https&&Env::bool('SESSION_SECURE'),'samesite'=>Env::get('SESSION_SAMESITE','Lax')??'Lax','path'=>'/']);session_start();
foreach(['X-Content-Type-Options'=>'nosniff','Referrer-Policy'=>'strict-origin-when-cross-origin','Permissions-Policy'=>'camera=(), microphone=(), geolocation=()','Content-Security-Policy'=>"default-src 'self'; style-src 'self'; script-src 'self'; img-src 'self' data:; frame-ancestors 'none'; form-action 'self'; base-uri 'self'",'X-Frame-Options'=>'DENY']as$k=>$v)header("$k: $v");
try{
 if((int)($_SERVER['CONTENT_LENGTH']??0)>1048576)throw new HttpException(413,'BODY_TOO_LARGE','Requisição muito grande.');$request=Request::capture();$repo=new AppRepository(ConnectionFactory::preconselho(Env::get('PRECONSELHO_DB_PATH',$root.'/storage/preconselho.db')??''));$api=new SecretariaApiClient();$view=new View(dirname(__DIR__).'/resources/views');$c=new WebController($repo,$view,$api);$binding=new BindingController($repo,$api);$management=new ManagementController($repo,$api,$view);$r=new Router();$auth=[new AuthMiddleware()];$admin=[new AuthMiddleware(),new RoleMiddleware(['ADMIN'])];$coord=[new AuthMiddleware(),new RoleMiddleware(['ADMIN','COORDENADOR'])];
 $r->add('GET','/login',fn()=>$c->loginForm());$r->add('POST','/login',fn($q)=>$c->login($q));$r->add('POST','/logout',fn($q)=>$c->logout($q),$auth);$r->add('GET','/',fn()=>$c->dashboard(),$auth);$r->add('GET','/relatorios/{id}',fn($q,$p)=>$c->report($q,$p),$auth);$r->add('POST','/relatorios/{id}',fn($q,$p)=>$c->save($q,$p),[new AuthMiddleware(),new RoleMiddleware(['PROFESSOR'])]);$r->add('POST','/coordenacao/relatorios/{id}',fn($q,$p)=>$c->review($q,$p),$coord);$r->add('POST','/admin/relatorios/{id}/reabrir',fn($q,$p)=>$management->reopen($q,$p),$admin);$r->add('GET','/admin',fn()=>$c->admin(),$admin);$r->add('GET','/admin/auditoria',fn($q)=>$management->audit($q),$admin);$r->add('POST','/admin/usuarios',fn($q)=>$c->createUser($q),$admin);$r->add('POST','/admin/usuarios/{id}/alternar',fn($q,$p)=>$management->toggleUser($q,$p),$admin);$r->add('POST','/admin/disciplinas',fn($q)=>$c->createDiscipline($q),$admin);$r->add('POST','/admin/vinculos',fn($q)=>$binding->create($q),$admin);$r->add('POST','/admin/periodos',fn($q)=>$c->period($q),$admin);$r->add('POST','/admin/periodos/{id}/abrir',fn($q,$p)=>$c->periodAction($q,$p,'open'),$admin);$r->add('POST','/admin/periodos/{id}/encerrar',fn($q,$p)=>$c->periodAction($q,$p,'close'),$coord);$r->add('GET','/consolidados',fn($q)=>$c->consolidated($q),$coord);$r->dispatch($request)->send();
}catch(HttpException$e){http_response_code($e->status);$title=$e->status.' — Erro';$message=$e->getMessage();$back='/';require dirname(__DIR__).'/resources/views/error.php';}catch(Throwable$e){error_log($e::class.': '.$e->getMessage());http_response_code(500);$title='500 — Erro';$message=Env::bool('APP_DEBUG')?$e->getMessage():'Não foi possível concluir a operação.';$back='/';require dirname(__DIR__).'/resources/views/error.php';}
