<?php declare(strict_types=1);
use Apc\Support\Module as ApcModule;
use PreConselho\Controllers\{BindingController,CollaborationController,ManagementController,PortalController,WebController};
use PreConselho\Integration\SecretariaApiClient;
use PreConselho\Middlewares\{AuthMiddleware,RoleMiddleware};
use PreConselho\Repositories\AppRepository;
use PreConselho\Services\PersistentLoginService;
use Shared\Database\ConnectionFactory;
use Shared\Env;
use Shared\Exceptions\HttpException;
use Shared\Http\{Request,Response,Router};
use Shared\Support\View;

$root=dirname(__DIR__,3);require $root.'/vendor/autoload.php';require $root.'/shared/Support/helpers.php';Env::load($root.'/.env');
date_default_timezone_set(Env::get('APP_TIMEZONE','America/Sao_Paulo')??'America/Sao_Paulo');$https=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';session_name('preconselho_session');session_set_cookie_params(['httponly'=>true,'secure'=>$https&&Env::bool('SESSION_SECURE'),'samesite'=>Env::get('SESSION_SAMESITE','Lax')??'Lax','path'=>'/']);session_start();
 foreach(['X-Content-Type-Options'=>'nosniff','Referrer-Policy'=>'strict-origin-when-cross-origin','Permissions-Policy'=>'camera=(), microphone=(), geolocation=()','Content-Security-Policy'=>"default-src 'self'; style-src 'self'; script-src 'self'; connect-src 'self' ws: wss:; img-src 'self' data: blob:; frame-src 'self' blob:; frame-ancestors 'none'; form-action 'self'; base-uri 'self'",'X-Frame-Options'=>'DENY']as$k=>$v)header("$k: $v");
try{
 $requestPath='/'.trim((string)(parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/'),'/');if($requestPath==='//')$requestPath='/';$bodyLimit=1048576;
 if($requestPath==='/apc/admin/calendario/analisar')$bodyLimit=max(1048576,Env::int('APC_CALENDAR_MAX_BYTES',15728640)+1048576);
 elseif($requestPath==='/apc/envios'||preg_match('#^/apc/entregas/[0-9]+/anexos$#',$requestPath))$bodyLimit=max(1048576,Env::int('APC_UPLOAD_MAX_BYTES',10485760)*($requestPath==='/apc/envios'?1:max(1,Env::int('APC_UPLOAD_MAX_FILES',5)))+1048576);
 if((int)($_SERVER['CONTENT_LENGTH']??0)>$bodyLimit)throw new HttpException(413,'BODY_TOO_LARGE','Requisição muito grande.');$request=Request::capture();$repo=new AppRepository(ConnectionFactory::preconselho(Env::get('PRECONSELHO_DB_PATH',$root.'/storage/preconselho.db')??''));$persistentDays=max(1,min(90,Env::int('PROFESSOR_LOGIN_DAYS',15)));$persistentLogin=new PersistentLoginService($repo->db,$persistentDays,$https&&Env::bool('SESSION_SECURE'),Env::get('SESSION_SAMESITE','Lax')??'Lax');$persistentCookie=$_COOKIE[PersistentLoginService::COOKIE_NAME]??null;if(!empty($_SESSION['user'])){$expires=(int)($_SESSION['user']['persistent_expires_at']??0);if($expires>0&&$expires<=time()){$persistentLogin->forget($persistentCookie);$_SESSION=[];session_regenerate_id(true);}elseif($expires===0&&($rememberedUntil=$persistentLogin->remember($_SESSION['user']))!==null)$_SESSION['user']['persistent_expires_at']=$rememberedUntil;}elseif(($restored=$persistentLogin->restore($persistentCookie))!==null){session_regenerate_id(true);$_SESSION['user']=$restored;}$api=new SecretariaApiClient();$view=new View(dirname(__DIR__).'/resources/views');$c=new WebController($repo,$view,$api,$persistentLogin);$portal=new PortalController($view);$binding=new BindingController($repo,$api);$management=new ManagementController($repo,$api,$view);$collaboration=new CollaborationController($repo);$apcInstance=null;$apcModule=static function()use(&$apcInstance,$repo,$api,$root):ApcModule{return$apcInstance??=new ApcModule(ConnectionFactory::apc(Env::get('APC_DB_PATH',$root.'/storage/apc.db')??''),$repo->db,$api,$root);};$r=new Router();$auth=[new AuthMiddleware()];$admin=[new AuthMiddleware(),new RoleMiddleware(['ADMIN'])];$coord=[new AuthMiddleware(),new RoleMiddleware(['ADMIN','COORDENADOR'])];$professor=[new AuthMiddleware(),new RoleMiddleware(['PROFESSOR'])];
 $r->add('POST','/internal/collaboration/snapshot',fn($q)=>$collaboration->snapshot($q));$r->add('POST','/internal/collaboration/save',fn($q)=>$collaboration->save($q));
 $r->add('GET','/documentos/{periodo}',fn($q,$p)=>$c->document($q,$p),$auth);$r->add('POST','/documentos/{periodo}/abertura/autosave',fn($q,$p)=>$c->autosaveOpening($q,$p),$coord);$r->add('POST','/documentos/{periodo}/turmas/{turma}/bloqueio',fn($q,$p)=>$c->lockDocumentClass($q,$p),$auth);$r->add('POST','/documentos/{periodo}/turmas/{turma}/bloqueio/liberar',fn($q,$p)=>$c->releaseDocumentClass($q,$p),$auth);$r->add('POST','/documentos/{periodo}/turmas/{turma}/autosave',fn($q,$p)=>$c->autosaveDocument($q,$p),$auth);$r->add('POST','/documentos/{periodo}/turmas/{turma}/finalizar',fn($q,$p)=>$c->finalizeClass($q,$p),[new AuthMiddleware(),new RoleMiddleware(['PROFESSOR'])]);$r->add('POST','/documentos/{periodo}/turmas/{turma}/professores/{professor}/reabrir',fn($q,$p)=>$c->reopenClassParticipation($q,$p),$coord);$r->add('GET','/documentos/{periodo}/professores/{professor}',fn($q,$p)=>Response::redirect('/documentos/'.$p['periodo']),$coord);
 $r->add('GET','/login',fn()=>$c->loginForm());$r->add('POST','/login',fn($q)=>$c->login($q));$r->add('POST','/logout',fn($q)=>$c->logout($q),$auth);$r->add('GET','/minha-senha',fn()=>$c->passwordForm(),$auth);$r->add('POST','/minha-senha',fn($q)=>$c->changePassword($q),$auth);$r->add('GET','/',fn()=>$portal->dashboard(),$auth);$r->add('GET','/conselho',fn()=>$c->dashboard(),$auth);$r->add('GET','/relatorios/{id}',fn($q,$p)=>$c->report($q,$p),$auth);$r->add('POST','/relatorios/{id}',fn($q,$p)=>$c->save($q,$p),$professor);$r->add('POST','/relatorios/{id}/autosave',fn($q,$p)=>$c->autosave($q,$p),$professor);$r->add('POST','/coordenacao/relatorios/{id}',fn($q,$p)=>$c->review($q,$p),$coord);$r->add('POST','/admin/relatorios/{id}/reabrir',fn($q,$p)=>$management->reopen($q,$p),$admin);$r->add('POST','/admin/relatorios/{id}/excluir',fn($q,$p)=>$management->deleteReport($q,$p),$admin);$r->add('GET','/admin',fn()=>$c->admin(),$admin);$r->add('GET','/admin/auditoria',fn($q)=>$management->audit($q),$admin);$r->add('POST','/admin/usuarios',fn($q)=>$c->createUser($q),$admin);$r->add('POST','/admin/usuarios/{id}/editar',fn($q,$p)=>$management->editUser($q,$p),$admin);$r->add('POST','/admin/usuarios/{id}/excluir',fn($q,$p)=>$management->deleteUser($q,$p),$admin);$r->add('POST','/admin/usuarios/{id}/alternar',fn($q,$p)=>$management->toggleUser($q,$p),$admin);$r->add('POST','/admin/vinculos',fn($q)=>$binding->create($q),$admin);$r->add('POST','/admin/vinculos/{id}/editar',fn($q,$p)=>$binding->update($q,$p),$admin);$r->add('POST','/admin/vinculos/{id}/alternar',fn($q,$p)=>$binding->toggle($q,$p),$admin);$r->add('POST','/admin/vinculos/{id}/excluir',fn($q,$p)=>$management->deleteBinding($q,$p),$admin);$r->add('POST','/admin/professores/{id}/vinculos/excluir',fn($q,$p)=>$management->deleteProfessorBindings($q,$p),$admin);$r->add('POST','/admin/periodos',fn($q)=>$c->period($q),$admin);$r->add('POST','/admin/periodos/{id}/abrir',fn($q,$p)=>$c->periodAction($q,$p,'open'),$admin);$r->add('POST','/admin/periodos/{id}/encerrar',fn($q,$p)=>$c->periodAction($q,$p,'close'),$coord);$r->add('POST','/admin/periodos/{id}/excluir',fn($q,$p)=>$management->deletePeriod($q,$p),$admin);$r->add('GET','/consolidados',fn($q)=>$c->consolidated($q),$coord);
 $r->add('GET','/apc',fn($q)=>$apcModule()->submissions->index($q),$auth);
 $r->add('POST','/apc/envios',fn($q)=>$apcModule()->submissions->upload($q),$auth);
 $r->add('POST','/apc/envios/{id}/excluir',fn($q,$p)=>$apcModule()->submissions->delete($q,$p),$coord);
 $r->add('GET','/apc/envios/{id}/visualizar',fn($q,$p)=>$apcModule()->submissions->preview($q,$p),$auth);
 $r->add('GET','/apc/envios/{id}/conteudo',fn($q,$p)=>$apcModule()->submissions->content($q,$p),$auth);
 $r->add('GET','/apc/envios/{id}/arquivo',fn($q,$p)=>$apcModule()->submissions->download($q,$p),$auth);
 $r->add('GET','/apc/calendario',fn($q)=>$apcModule()->calendar->index($q),$auth);
 $r->add('GET','/apc/eventos/{id}',fn($q,$p)=>$apcModule()->calendar->show($q,$p),$auth);
 $r->add('GET','/apc/habilidades',fn($q)=>$apcModule()->curriculum->search($q),$auth);
 $r->add('GET','/apc/planos/novo',fn($q)=>$apcModule()->plans->createForm($q),$professor);
 $r->add('POST','/apc/planos',fn($q)=>$apcModule()->plans->create($q),$professor);
 $r->add('GET','/apc/planos/{id}',fn($q,$p)=>$apcModule()->plans->show($q,$p),$auth);
 $r->add('POST','/apc/planos/{id}',fn($q,$p)=>$apcModule()->plans->update($q,$p),$professor);
 $r->add('POST','/apc/planos/{id}/finalizar',fn($q,$p)=>$apcModule()->plans->finalize($q,$p),$professor);
 $r->add('POST','/apc/planos/{id}/reabrir',fn($q,$p)=>$apcModule()->plans->reopen($q,$p),$coord);
 $r->add('GET','/apc/planos/{id}/entregas',fn($q,$p)=>$apcModule()->deliveries->index($q,$p),$auth);
 $r->add('POST','/apc/planos/{id}/entregas/{aluno}',fn($q,$p)=>$apcModule()->deliveries->save($q,$p),$professor);
 $r->add('POST','/apc/entregas/{id}/anexos',fn($q,$p)=>$apcModule()->attachments->upload($q,$p),$professor);
 $r->add('GET','/apc/anexos/{id}',fn($q,$p)=>$apcModule()->attachments->download($q,$p),$auth);
 $r->add('POST','/apc/anexos/{id}/excluir',fn($q,$p)=>$apcModule()->attachments->delete($q,$p),$professor);
 $r->add('GET','/apc/relatorios',fn($q)=>$apcModule()->reports->index($q),$coord);
 $r->add('GET','/apc/admin',fn($q)=>$apcModule()->admin->index($q),$admin);
 $r->add('GET','/apc/admin/curriculo',fn($q)=>$apcModule()->curriculumAdmin->index($q),$admin);
 $r->add('POST','/apc/admin/curriculo/importar',fn($q)=>$apcModule()->curriculumAdmin->import($q),$admin);
 $r->add('POST','/apc/admin/curriculo/componentes',fn($q)=>$apcModule()->curriculumAdmin->createComponent($q),$admin);
 $r->add('POST','/apc/admin/curriculo/componentes/{id}',fn($q,$p)=>$apcModule()->curriculumAdmin->updateComponent($q,$p),$admin);
 $r->add('POST','/apc/admin/curriculo/componentes/{id}/alternar',fn($q,$p)=>$apcModule()->curriculumAdmin->toggleComponent($q,$p),$admin);
 $r->add('POST','/apc/admin/curriculo/habilidades',fn($q)=>$apcModule()->curriculumAdmin->createAbility($q),$admin);
 $r->add('POST','/apc/admin/curriculo/habilidades/{id}',fn($q,$p)=>$apcModule()->curriculumAdmin->updateAbility($q,$p),$admin);
 $r->add('POST','/apc/admin/curriculo/habilidades/{id}/alternar',fn($q,$p)=>$apcModule()->curriculumAdmin->toggleAbility($q,$p),$admin);
 $r->add('POST','/apc/admin/calendario/analisar',fn($q)=>$apcModule()->admin->analyzeSchoolCalendar($q),$admin);
 $r->add('GET','/apc/admin/calendario/revisar',fn($q)=>$apcModule()->admin->reviewSchoolCalendar($q),$admin);
 $r->add('POST','/apc/admin/calendario/confirmar',fn($q)=>$apcModule()->admin->confirmSchoolCalendar($q),$admin);
 $r->add('POST','/apc/admin/calendario/importar',fn($q)=>$apcModule()->admin->importSchoolCalendar($q),$admin);
 $r->add('POST','/apc/admin/eventos',fn($q)=>$apcModule()->admin->createEvent($q),$admin);
 $r->add('POST','/apc/admin/eventos/{id}',fn($q,$p)=>$apcModule()->admin->updateEvent($q,$p),$admin);
 $r->add('POST','/apc/admin/eventos/{id}/cancelar',fn($q,$p)=>$apcModule()->admin->cancelEvent($q,$p),$admin);
 $r->add('POST','/apc/admin/eventos/{id}/reativar',fn($q,$p)=>$apcModule()->admin->reactivateEvent($q,$p),$admin);
 $r->add('POST','/apc/admin/parametros',fn($q)=>$apcModule()->admin->updateSettings($q),$admin);
 $r->dispatch($request)->send();
}catch(HttpException$e){if(str_starts_with((string)(parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)??''),'/internal/collaboration/'))Response::json(['success'=>false,'error'=>$e->errorCode,'message'=>$e->getMessage()],$e->status)->send();http_response_code($e->status);$title=$e->status.' — Erro';$message=$e->getMessage();$back='/';require dirname(__DIR__).'/resources/views/error.php';}catch(Throwable$e){error_log($e::class.': '.$e->getMessage());if(str_starts_with((string)(parse_url($_SERVER['REQUEST_URI']??'',PHP_URL_PATH)??''),'/internal/collaboration/'))Response::json(['success'=>false,'error'=>'INTERNAL_ERROR','message'=>Env::bool('APP_DEBUG')?$e->getMessage():'Falha interna no serviço de colaboração.'],500)->send();http_response_code(500);$title='500 — Erro';$message=Env::bool('APP_DEBUG')?$e->getMessage():'Não foi possível concluir a operação.';$back='/';require dirname(__DIR__).'/resources/views/error.php';}
