<?php ob_start();?>
<section class="page-heading"><div><p class="eyebrow">Documento da escola</p><h1>Conselho coletivo</h1><p>Uma seção compartilhada para cada turma, reunindo as contribuições de todos os professores.</p></div><div class="actions"><a class="button" href="?formato=csv">Exportar planilha (CSV)</a><button class="primary" type="button" data-print-page>Imprimir</button></div></section>
<section class="card">
    <div class="section-heading"><div><h2>Relatos coletivos por turma</h2><p><?=count($rows)?> seção(ões) preenchida(s)</p></div><?php if($rows):?><label class="search"><span class="sr-only">Buscar no documento</span><span aria-hidden="true">⌕</span><input type="search" placeholder="Buscar período ou turma" data-table-search="#consolidated-table"></label><?php endif;?></div>
    <?php if(!$rows):?><div class="empty-state"><h3>Ainda não há contribuições</h3><p>Os textos aparecerão aqui conforme os professores preencherem o documento coletivo.</p></div><?php else:?>
    <div class="table"><table id="consolidated-table"><thead><tr><th>Período</th><th>Turno</th><th>Turma</th><th>Relato coletivo</th><th>Última atualização</th></tr></thead><tbody><?php foreach($rows as$row):?><tr><td data-label="Período"><strong><?=e($row['periodo'])?></strong><small><?=e($row['ano_letivo'])?></small></td><td data-label="Turno"><?=e($row['turno']==='VESPERTINO'?'Vespertino':'Matutino')?></td><td data-label="Turma"><?=e($row['turma'])?></td><td data-label="Relato" class="consolidated-narrative"><?=nl2br(e($row['relato']))?></td><td data-label="Última atualização"><strong><?=e($row['atualizado_por'])?></strong><small><?=e(date('d/m/Y H:i',strtotime($row['atualizado_em'])))?></small></td></tr><?php endforeach;?></tbody></table></div>
    <?php endif;?>
</section>
<?php $content=ob_get_clean();require __DIR__.'/layout.php';
