<?php
$isTeacher=($_SESSION['user']['perfil']??'')==='PROFESSOR';
$labels=['PENDENTE'=>'A preencher','RASCUNHO'=>'Em rascunho','ENVIADO'=>'Aguardando conferência','DEVOLVIDO'=>'Precisa de ajuste','APROVADO'=>'Aprovado'];
$descriptions=['PENDENTE'=>'Ainda não iniciado','RASCUNHO'=>'Salvo para continuar depois','ENVIADO'=>'Enviado para a coordenação','DEVOLVIDO'=>'Devolvido pela coordenação','APROVADO'=>'Conferência concluída'];
$needsAction=array_values(array_filter($reports,static fn($r)=>in_array($r['status'],['PENDENTE','RASCUNHO','DEVOLVIDO'],true)));
$alreadySent=array_values(array_filter($reports,static fn($r)=>in_array($r['status'],['ENVIADO','APROVADO'],true)));
$renderTeacherRows=static function(array $items)use($labels):void{foreach($items as$r):?><tr data-status="<?=e($r['status'])?>"><td data-label="Turma e disciplina"><strong><?=e($r['turma_nome_snapshot'])?></strong><small><?=e($r['disciplina'])?></small></td><td data-label="Período"><?=e($r['periodo'])?></td><td data-label="Situação"><span class="badge status-<?=e(strtolower($r['status']))?>"><?=e($labels[$r['status']]??$r['status'])?></span></td><td data-label="Prazo"><time datetime="<?=e($r['data_fim'])?>"><?=e(date('d/m/Y',strtotime($r['data_fim'])))?></time></td><td class="row-action"><a class="button <?=in_array($r['status'],['PENDENTE','RASCUNHO','DEVOLVIDO'],true)?'primary':''?>" href="/relatorios/<?=e($r['id'])?>"><?=in_array($r['status'],['PENDENTE','RASCUNHO','DEVOLVIDO'],true)?'Preencher':'Visualizar'?> <span aria-hidden="true">→</span></a></td></tr><?php endforeach;};
ob_start();?><section class="page-heading"><div><p class="eyebrow"><?=$isTeacher?'Área do professor':'Área da coordenação'?></p><h1>Olá, <?=e(explode(' ',trim($_SESSION['user']['nome']))[0])?>!</h1><p><?=$isTeacher?'Veja suas turmas, preencha o que está pendente e acompanhe os relatórios enviados.':'Acompanhe os envios por professor, confira as turmas e identifique rapidamente as pendências.'?></p></div></section>
<?php if($isTeacher):?>
<div class="metrics teacher-summary" aria-label="Resumo dos meus relatórios"><article class="metric static status-card-devolvido"><span class="metric-label">Precisam da sua ação</span><strong><?=count($needsAction)?></strong><small>Pendentes, rascunhos ou devolvidos</small></article><article class="metric static status-card-enviado"><span class="metric-label">Já enviados</span><strong><?=count($alreadySent)?></strong><small>Na coordenação ou aprovados</small></article><article class="metric static"><span class="metric-label">Total de turmas</span><strong><?=count($reports)?></strong><small>Relatórios atribuídos a você</small></article></div>
<section class="card work-list priority-list"><div class="section-heading"><div><p class="eyebrow">Prioridade</p><h2>Turmas que precisam de preenchimento</h2><p><?=count($needsAction)?> relatório(s) aguardando sua ação</p></div><?php if($needsAction):?><label class="search"><span class="sr-only">Buscar turma pendente</span><span aria-hidden="true">⌕</span><input type="search" placeholder="Buscar turma ou disciplina" data-table-search="#teacher-pending"></label><?php endif;?></div><?php if(!$needsAction):?><div class="empty-state compact"><span aria-hidden="true">✓</span><h3>Tudo em dia</h3><p>Você não possui relatórios aguardando preenchimento ou correção.</p></div><?php else:?><div class="table"><table id="teacher-pending"><thead><tr><th>Turma e disciplina</th><th>Período</th><th>Situação</th><th>Prazo</th><th><span class="sr-only">Ação</span></th></tr></thead><tbody><?php $renderTeacherRows($needsAction);?></tbody></table></div><?php endif;?></section>
<section class="card work-list"><div class="section-heading"><div><p class="eyebrow">Acompanhamento</p><h2>Relatórios que você já enviou</h2><p><?=count($alreadySent)?> relatório(s) enviado(s)</p></div><?php if($alreadySent):?><label class="search"><span class="sr-only">Buscar relatório enviado</span><span aria-hidden="true">⌕</span><input type="search" placeholder="Buscar turma ou disciplina" data-table-search="#teacher-sent"></label><?php endif;?></div><?php if(!$alreadySent):?><div class="empty-state compact"><p>Nenhum relatório foi enviado ainda.</p></div><?php else:?><div class="table"><table id="teacher-sent"><thead><tr><th>Turma e disciplina</th><th>Período</th><th>Situação</th><th>Prazo</th><th><span class="sr-only">Ação</span></th></tr></thead><tbody><?php $renderTeacherRows($alreadySent);?></tbody></table></div><?php endif;?></section>
<?php else:$notFinished=$counts['PENDENTE']+$counts['RASCUNHO']+$counts['DEVOLVIDO'];?>
<div class="metrics coordination-summary" aria-label="Resumo da coordenação"><article class="metric static status-card-devolvido"><span class="metric-label">Ainda não concluídos</span><strong><?=e($notFinished)?></strong><small>Aguardando professor</small></article><article class="metric static status-card-enviado"><span class="metric-label">Prontos para conferir</span><strong><?=e($counts['ENVIADO'])?></strong><small>Enviados pelos professores</small></article><article class="metric static status-card-aprovado"><span class="metric-label">Aprovados</span><strong><?=e($counts['APROVADO'])?></strong><small>Conferência concluída</small></article><article class="metric static"><span class="metric-label">Professores</span><strong><?=count($professorProgress)?></strong><small>Com relatórios atribuídos</small></article></div>
<section class="card work-list"><div class="section-heading"><div><p class="eyebrow">Acompanhamento da equipe</p><h2>Situação por professor</h2><p><?=count($professorProgress)?> professor(es) com relatórios</p></div><?php if($professorProgress):?><label class="search"><span class="sr-only">Buscar professor ou turma</span><span aria-hidden="true">⌕</span><input id="professor-search" type="search" placeholder="Buscar professor, turma ou disciplina"></label><?php endif;?></div>
<?php if(!$professorProgress):?><div class="empty-state"><span aria-hidden="true">✓</span><h3>Nenhum relatório gerado</h3><p>Os professores aparecerão após a abertura de um período com vínculos ativos.</p></div><?php else:?><div class="professor-list"><?php foreach($professorProgress as$p):$allDone=$p['pendentes']===0&&$p['enviados']===0;$nothingSent=$p['enviados']===0&&$p['aprovados']===0;$state=$allDone?'Concluído':($nothingSent?'Ainda não enviou':($p['pendentes']>0?'Envio parcial':'Aguardando conferência'));$stateClass=$allDone?'aprovado':($nothingSent?'devolvido':($p['pendentes']>0?'rascunho':'enviado'));?><details class="professor-card" <?=($p['pendentes']>0||$p['enviados']>0)?'open':''?>><summary><span class="professor-identity"><span class="avatar" aria-hidden="true"><?=e(mb_strtoupper(mb_substr($p['nome'],0,1)))?></span><span><strong><?=e($p['nome'])?></strong><small><?=e($p['total'])?> relatório(s) · <?=e($p['pendentes'])?> não concluído(s) · <?=e($p['enviados'])?> para conferir</small></span></span><span class="badge status-<?=e($stateClass)?>"><?=e($state)?></span></summary><div class="table"><table><thead><tr><th>Turma e disciplina</th><th>Período</th><th>Situação</th><th>Prazo</th><th><span class="sr-only">Ação</span></th></tr></thead><tbody><?php foreach($p['reports'] as$r):?><tr><td data-label="Turma e disciplina"><strong><?=e($r['turma_nome_snapshot'])?></strong><small><?=e($r['disciplina'])?></small></td><td data-label="Período"><?=e($r['periodo'])?></td><td data-label="Situação"><span class="badge status-<?=e(strtolower($r['status']))?>"><?=e($labels[$r['status']]??$r['status'])?></span></td><td data-label="Prazo"><?=e(date('d/m/Y',strtotime($r['data_fim'])))?></td><td class="row-action"><a class="button <?=$r['status']==='ENVIADO'?'primary':''?>" href="/relatorios/<?=e($r['id'])?>"><?=$r['status']==='ENVIADO'?'Conferir':'Visualizar'?> <span aria-hidden="true">→</span></a></td></tr><?php endforeach;?></tbody></table></div></details><?php endforeach;?></div><div id="professor-empty" class="empty-state compact" hidden><p>Nenhum professor corresponde à busca.</p></div><?php endif;?></section><?php endif;?><?php $content=ob_get_clean();require __DIR__.'/layout.php';
