<?php
use PreConselho\Support\Csrf;
$content=$content??'';
$user=$_SESSION['user']??null;
$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
$roleLabels=['ADMIN'=>'Administrador','COORDENADOR'=>'Coordenação','PROFESSOR'=>'Professor'];
$isActive=static fn(string $route):string=>($route==='/'?$path==='/':str_starts_with($path,$route))?' active':'';
?><!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#173f5f"><title><?=e($title??'Pré-Conselho')?> · Pré-Conselho Escolar</title><link rel="stylesheet" href="/assets/app.css"></head>
<body><a class="skip" href="#conteudo">Pular para o conteúdo</a>
<header class="app-header"><div class="header-inner"><a class="brand" href="/" aria-label="Ir para o painel"><span class="brand-mark" aria-hidden="true">PC</span><span><strong>Pré-Conselho</strong><small>Organização pedagógica</small></span></a>
<?php if($user):?><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav"><span aria-hidden="true">☰</span> Menu</button><nav id="main-nav" aria-label="Principal"><a class="<?=$isActive('/')?>" href="/"><span aria-hidden="true">⌂</span> Painel</a><?php if($user['perfil']!=='PROFESSOR'):?><a class="<?=$isActive('/consolidados')?>" href="/consolidados"><span aria-hidden="true">▤</span> Consolidado</a><?php endif;?><?php if($user['perfil']==='ADMIN'):?><a class="<?=$isActive('/admin')?>" href="/admin"><span aria-hidden="true">⚙</span> Administração</a><?php endif;?></nav><div class="user-area"><span class="user-copy"><strong><?=e($user['nome'])?></strong><small><?=e($roleLabels[$user['perfil']]??$user['perfil'])?></small></span><form method="post" action="/logout"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><button class="button ghost" title="Encerrar sessão">Sair</button></form></div><?php endif;?></div></header>
<main id="conteudo"><?php if(!empty($_SESSION['flash'])):?><div class="flash" role="status"><span aria-hidden="true">✓</span><span><?=e($_SESSION['flash']);unset($_SESSION['flash']);?></span></div><?php endif;?><?=$content?><?php if(isset($report)&&($user['perfil']??'')==='ADMIN'&&$report['status']==='APROVADO'&&$report['periodo_status']!=='ENCERRADO'):?><section class="card danger-zone"><div><p class="eyebrow">Ação administrativa</p><h2>Reabrir relatório aprovado</h2><p>O relatório voltará ao professor para ajustes e a ação ficará registrada no histórico.</p></div><form method="post" action="/admin/relatorios/<?=e($report['id'])?>/reabrir"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><label>Motivo da reabertura <textarea name="justificativa" required maxlength="2000" placeholder="Explique por que o relatório precisa ser alterado"></textarea></label><button class="danger" data-confirm="Confirma a reabertura deste relatório?">Reabrir relatório</button></form></section><?php endif;?></main><footer>Pré-Conselho Escolar <span>•</span> Informações pedagógicas organizadas com segurança</footer><script src="/assets/app.js" defer></script></body></html>
