<?php
use PreConselho\Support\Csrf;
$content=$content??'';
$user=$_SESSION['user']??null;
$path=parse_url($_SERVER['REQUEST_URI']??'/',PHP_URL_PATH)?:'/';
$isLogin=$path==='/login'&&!$user;
$isPortal=$path==='/';
$isApc=str_starts_with($path,'/apc');
$isCouncil=!$isPortal&&!$isApc&&!$isLogin;
$roleLabels=['ADMIN'=>'Administrador','COORDENADOR'=>'Coordenação','PROFESSOR'=>'Professor'];
$brandTitle=$isPortal?'Gestão Pedagógica':($isApc?'APCs':'Conselho de Classe');
$moduleName=$isPortal?'Visão geral':($isApc?'Atividades Pedagógicas Complementares':'Conselho de Classe');
$nameParts=$user?preg_split('/\s+/',trim((string)$user['nome'])):[];$userInitials=$user?mb_strtoupper(mb_substr((string)($nameParts[0]??''),0,1).mb_substr((string)($nameParts[count($nameParts)-1]??''),0,1)):'';
$apcCalendarActive=$isApc&&(str_starts_with($path,'/apc/calendario')||str_starts_with($path,'/apc/eventos/'));$apcReportsActive=str_starts_with($path,'/apc/relatorios');$apcAdminActive=$path==='/apc/admin';$apcCurriculumActive=str_starts_with($path,'/apc/admin/curriculo');$apcHomeActive=$isApc&&!$apcCalendarActive&&!$apcReportsActive&&!$apcAdminActive&&!$apcCurriculumActive;
$councilConsolidatedActive=str_starts_with($path,'/consolidados');$councilAdminActive=str_starts_with($path,'/admin');$councilHomeActive=$isCouncil&&!$councilConsolidatedActive&&!$councilAdminActive;
$assetVersion=static function(string $file):string{$path=dirname(__DIR__,2).'/public/assets/'.$file;$modified=is_file($path)?filemtime($path):false;return $modified===false?'1':(string)$modified;};
?><!doctype html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#173f5f"><title><?=e($title??$brandTitle)?> · Gestão Pedagógica</title><link rel="stylesheet" href="/assets/app.css?v=<?=e($assetVersion('app.css'))?>"></head>
<body class="<?=trim(($isLogin?'login-page ':'').($isApc?'apc-page ':''))?>"><a class="skip" href="#conteudo">Pular para o conteúdo</a>
<?php if(!$isLogin):?><header class="app-header"><div class="header-shell"><div class="header-top"><a class="school-brand" href="/" aria-label="EE São José — ir para a visão geral"><span class="school-logo-frame" aria-hidden="true"><img src="/assets/logo_escola.png" alt=""></span><span class="school-brand-copy"><strong>EE São José</strong><small>Gestão Pedagógica</small></span></a><?php if($user):?><span class="module-context"><small>Área atual</small><strong><?=e($moduleName)?></strong></span><div class="user-area desktop-user"><span class="user-avatar" aria-hidden="true"><?=e($userInitials)?></span><span class="user-copy"><strong><?=e($user['nome'])?></strong><small><?=e($roleLabels[$user['perfil']]??$user['perfil'])?></small></span><form method="post" action="/logout"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><button class="header-logout" title="Encerrar sessão">Sair</button></form></div><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="main-nav"><span aria-hidden="true">☰</span><span data-menu-label>Menu</span></button><?php endif;?></div>
<?php if($user):?><nav id="main-nav" class="header-navigation" aria-label="Navegação principal"><div class="nav-group nav-systems"><span class="nav-group-label">Sistemas</span><a class="nav-system-link<?=$isPortal?' active':''?>" href="/"><span aria-hidden="true">⌂</span> Visão geral</a><a class="nav-system-link<?=$isCouncil?' active':''?>" href="/conselho"><span class="nav-code" aria-hidden="true">CC</span> Conselho de Classe</a><a class="nav-system-link<?=$isApc?' active':''?>" href="/apc"><span class="nav-code" aria-hidden="true">APC</span> APC</a></div><?php if(!$isPortal):?><span class="nav-separator" aria-hidden="true"></span><div class="nav-group nav-context"><span class="nav-group-label">Nesta área</span><?php if($isApc):?><a class="<?=$apcHomeActive?'active':''?>" href="/apc">Painel</a><a class="<?=$apcCalendarActive?'active':''?>" href="/apc/calendario">Calendário</a><?php if($user['perfil']!=='PROFESSOR'):?><a class="<?=$apcReportsActive?'active':''?>" href="/apc/relatorios">Relatórios</a><?php endif;?><?php if($user['perfil']==='ADMIN'):?><a class="<?=$apcAdminActive?'active':''?>" href="/apc/admin">Eventos e parâmetros</a><a class="<?=$apcCurriculumActive?'active':''?>" href="/apc/admin/curriculo">Currículo</a><?php endif;?><?php else:?><a class="<?=$councilHomeActive?'active':''?>" href="/conselho">Painel do Conselho</a><?php if($user['perfil']!=='PROFESSOR'):?><a class="<?=$councilConsolidatedActive?'active':''?>" href="/consolidados">Consolidado</a><?php endif;?><?php if($user['perfil']==='ADMIN'):?><a class="<?=$councilAdminActive?'active':''?>" href="/admin">Administração</a><?php endif;?><?php endif;?></div><?php endif;?><div class="mobile-account"><span class="user-avatar" aria-hidden="true"><?=e($userInitials)?></span><span class="user-copy"><strong><?=e($user['nome'])?></strong><small><?=e($roleLabels[$user['perfil']]??$user['perfil'])?></small></span><form method="post" action="/logout"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><button class="header-logout">Sair</button></form></div></nav><?php endif;?></div></header><?php endif;?>
<main id="conteudo"><?php if(!empty($_SESSION['flash'])):?><div class="flash" role="status"><span aria-hidden="true">✓</span><span><?=e($_SESSION['flash']);unset($_SESSION['flash']);?></span></div><?php endif;?><?=$content?><?php if(isset($report)&&($user['perfil']??'')==='ADMIN'&&$report['status']==='APROVADO'&&$report['periodo_status']!=='ENCERRADO'):?><section class="card danger-zone"><div><p class="eyebrow">Ação administrativa</p><h2>Reabrir relatório aprovado</h2><p>O relatório voltará ao professor para ajustes e a ação ficará registrada no histórico.</p></div><form method="post" action="/admin/relatorios/<?=e($report['id'])?>/reabrir"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><label>Motivo da reabertura <textarea name="justificativa" required maxlength="2000" placeholder="Explique por que o relatório precisa ser alterado"></textarea></label><button class="danger" data-confirm="Confirma a reabertura deste relatório?">Reabrir relatório</button></form></section><?php endif;?></main><?php if(!$isLogin):?><footer><?=e($brandTitle)?> <span>•</span> Gestão pedagógica da escola</footer><?php endif;?><script src="/assets/app.js?v=<?=e($assetVersion('app.js'))?>" defer></script><?php if(is_file(dirname(__DIR__,2).'/public/assets/collaboration.js')):?><script src="/assets/collaboration.js?v=<?=e($assetVersion('collaboration.js'))?>" defer></script><?php endif;?></body></html>
