<?php
use PreConselho\Support\Csrf;
$byId=[];foreach($selected as$x)$byId[$x['aluno_externo_id']]=$x;
$canEdit=$_SESSION['user']['perfil']==='PROFESSOR'&&in_array($report['status'],['PENDENTE','RASCUNHO','DEVOLVIDO'],true);
$canReview=$_SESSION['user']['perfil']!=='PROFESSOR'&&$report['status']==='ENVIADO';
$statusLabels=['PENDENTE'=>'A preencher','RASCUNHO'=>'Em rascunho','ENVIADO'=>'Aguardando conferência','DEVOLVIDO'=>'Precisa de ajuste','APROVADO'=>'Aprovado'];
ob_start();?><nav class="breadcrumbs" aria-label="Caminho"><a href="/">Painel</a> <span aria-hidden="true">›</span> Relatório</nav><section class="page-heading"><div><p class="eyebrow"><?=e($report['periodo'])?></p><h1><?=e($report['turma_nome_snapshot'])?></h1><p><?=e($report['disciplina'])?> · Professor(a) <?=e($report['professor_nome'])?></p></div><span class="badge status-<?=e(strtolower($report['status']))?>"><?=e($statusLabels[$report['status']]??$report['status'])?></span></section>
<section class="card"><h2>Informações do relatório</h2><dl class="identity"><div><dt>Período</dt><dd><?=e($report['periodo'])?></dd></div><div><dt>Etapa</dt><dd><?=e($report['etapa'])?></dd></div><div><dt>Prazo para envio</dt><dd><?=e(date('d/m/Y',strtotime($report['data_fim'])))?></dd></div></dl><?php if($report['status']==='DEVOLVIDO'):?><p class="error" role="alert"><span aria-hidden="true">!</span><span>Este relatório foi devolvido e precisa de ajustes. Consulte o histórico no fim da página.</span></p><?php endif;?></section>
<?php if($apiError):?><p class="error" role="alert"><span aria-hidden="true">!</span><span><?=e($apiError)?></span></p><?php endif;?>
<form method="post"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="versao" value="<?=e($report['versao'])?>"><section class="card form-section"><p class="eyebrow">Etapa 1</p><h2>Alunos indicados para o RAV</h2><p class="helper">Informe se há estudantes que precisam ser destacados neste relatório.</p><fieldset><legend>Existem alunos indicados para o RAV?</legend><label><input type="radio" name="possui_alunos_rav" value="1" <?=$report['possui_alunos_rav']==='1'?'checked':''?> <?=!$canEdit?'disabled':''?>> Sim, há alunos indicados</label><label><input type="radio" name="possui_alunos_rav" value="0" <?=$report['possui_alunos_rav']==='0'?'checked':''?> <?=!$canEdit?'disabled':''?>> Não há alunos indicados</label></fieldset>
<div class="form-section-header"><div><h2>Selecione e descreva os alunos</h2><p class="helper"><?=count($students)?> aluno(s) na turma · marque somente quem será incluído</p></div><?php if($students):?><label class="search"><span class="sr-only">Buscar aluno</span><span aria-hidden="true">⌕</span><input id="student-search" type="search" placeholder="Buscar aluno pelo nome"></label><?php endif;?></div><div class="student-list"><?php if(!$students&&!$apiError):?><div class="empty-state compact"><p>Nenhum aluno encontrado nesta turma.</p></div><?php endif;?><?php foreach($students as$a):$x=$byId[$a['id']]??[];?><details <?=isset($byId[$a['id']])?'open':''?>><summary><label><input type="checkbox" name="alunos[<?=e($a['id'])?>][selecionado]" value="1" <?=isset($byId[$a['id']])?'checked':''?> <?=!$canEdit?'disabled':''?>> <?=e($a['nome_completo'])?> <small>· Nascimento: <?=e(date('d/m/Y',strtotime($a['data_nascimento'])))?></small></label></summary><div class="student-fields"><label>Nota<input type="number" step="0.1" min="0" max="10" name="alunos[<?=e($a['id'])?>][nota]" value="<?=e($x['nota']??'')?>"></label><label>Motivo do RAV<textarea name="alunos[<?=e($a['id'])?>][motivo_rav]" placeholder="Por que o aluno foi indicado?"><?=e($x['motivo_rav']??'')?></textarea></label><label>Dificuldades observadas<textarea name="alunos[<?=e($a['id'])?>][dificuldades]" placeholder="Descreva as principais dificuldades"><?=e($x['dificuldades']??'')?></textarea></label><label>Intervenções realizadas<textarea name="alunos[<?=e($a['id'])?>][intervencoes]" placeholder="O que já foi feito para apoiar o aluno?"><?=e($x['intervencoes']??'')?></textarea></label><label>Observações<textarea name="alunos[<?=e($a['id'])?>][observacao]" placeholder="Outras informações relevantes"><?=e($x['observacao']??'')?></textarea></label></div></details><?php endforeach;?></div></section>
<section class="card form-section"><p class="eyebrow">Etapa 2</p><h2>Visão geral da turma</h2><p class="helper">Registre informações que se aplicam à turma como um todo.</p><label>Dificuldades gerais<textarea name="dificuldades_gerais" <?=!$canEdit?'readonly':''?> placeholder="Quais dificuldades foram percebidas na turma?"><?=e($report['dificuldades_gerais'])?></textarea></label><label>Medidas adotadas<textarea name="medidas_adotadas" <?=!$canEdit?'readonly':''?> placeholder="Quais estratégias e intervenções foram realizadas?"><?=e($report['medidas_adotadas'])?></textarea></label><label>Observações do professor<textarea name="observacoes_professor" <?=!$canEdit?'readonly':''?> placeholder="Inclua outras informações importantes para o conselho"><?=e($report['observacoes_professor'])?></textarea></label><?php if($canEdit):?><div class="actions"><button name="acao" value="rascunho">Salvar para continuar depois</button><button name="acao" value="enviar" class="primary" data-confirm="O relatório será enviado para a coordenação. Deseja continuar?">Enviar para conferência <span aria-hidden="true">→</span></button></div><?php endif;?></section></form>
<?php if($canReview):?><section class="card review-card"><p class="eyebrow">Conferência da coordenação</p><h2>Registrar parecer</h2><p class="helper">Aprove o relatório ou devolva ao professor com uma orientação clara sobre o ajuste necessário.</p><form method="post" action="/coordenacao/relatorios/<?=e($report['id'])?>"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><label>Parecer da coordenação<textarea name="parecer" placeholder="Registre o parecer sobre as informações apresentadas"></textarea></label><label>Orientação para devolução<textarea name="justificativa" placeholder="Obrigatória ao devolver: explique exatamente o que deve ser corrigido"></textarea></label><div class="actions"><button class="danger" name="acao" value="devolver">Devolver para ajustes</button><button class="primary" name="acao" value="aprovar" data-confirm="Confirma a aprovação deste relatório?">Aprovar relatório</button></div></form></section><?php endif;?>
<section class="card"><p class="eyebrow">Registro</p><h2>Histórico do relatório</h2><?php if(!$history):?><p class="helper">Ainda não há movimentações registradas.</p><?php else:?><ol class="history"><?php foreach($history as$h):?><li><strong><?=e($statusLabels[$h['status_anterior']]??$h['status_anterior'])?> → <?=e($statusLabels[$h['status_novo']]??$h['status_novo'])?></strong><br><small><?=e(date('d/m/Y H:i',strtotime($h['criado_em'])))?> por <?=e($h['usuario_nome'])?></small><?php if(trim((string)$h['justificativa'])!==''):?><p><?=e($h['justificativa'])?></p><?php endif;?></li><?php endforeach;?></ol><?php endif;?></section><?php $content=ob_get_clean();require __DIR__.'/layout.php';
