<?php
use PreConselho\Support\Csrf;
$byId=[];foreach($selected as$x)$byId[$x['aluno_externo_id']]=$x;
$canEdit=$_SESSION['user']['perfil']==='PROFESSOR'&&in_array($report['status'],['PENDENTE','RASCUNHO','DEVOLVIDO'],true);
$canReview=$_SESSION['user']['perfil']!=='PROFESSOR'&&$report['status']==='ENVIADO';
$statusLabels=['PENDENTE'=>'A preencher','RASCUNHO'=>'Em rascunho','ENVIADO'=>'Aguardando conferência','DEVOLVIDO'=>'Precisa de ajuste','APROVADO'=>'Aprovado'];
$classObservations=['ALUNOS_FALTOSOS'=>'Alunos faltosos','DIFICULDADE_APRENDIZAGEM'=>'Dificuldade de aprendizagem','INDISCIPLINA'=>'Indisciplina','DESINTERESSE'=>'Desinteresse','FALTA_ACOMPANHAMENTO_FAMILIAR'=>'Falta de acompanhamento familiar','PROBLEMAS_EMOCIONAIS'=>'Problemas emocionais','DIFICULDADE_SOCIALIZACAO'=>'Dificuldade de socialização','PROBLEMAS_SAUDE'=>'Problemas de saúde','OUTROS'=>'Outros'];
$adoptedMeasures=['CONVERSA_ALUNO'=>'Conversa individual com o aluno','REUNIAO_RESPONSAVEIS'=>'Reunião com responsáveis','ENCAMINHAMENTO_COORDENACAO'=>'Encaminhamento à coordenação pedagógica','RECUPERACAO_REFORCO'=>'Recuperação paralela ou reforço','ATIVIDADES_DIFERENCIADAS'=>'Atividades diferenciadas','MUDANCA_ESTRATEGIA'=>'Mudança de estratégia ou metodologia','ACOMPANHAMENTO_INDIVIDUAL'=>'Acompanhamento individual','OUTROS'=>'Outros'];
$checkedObservations=json_decode((string)($report['observacoes_turma_json']??'[]'),true);if(!is_array($checkedObservations))$checkedObservations=[];
$checkedMeasures=json_decode((string)($report['medidas_adotadas_json']??'[]'),true);if(!is_array($checkedMeasures))$checkedMeasures=[];
$reportDate=!empty($report['enviado_em'])?date('d/m/Y',strtotime($report['enviado_em'])):date('d/m/Y');
ob_start();?><nav class="breadcrumbs" aria-label="Caminho"><a href="/">Painel</a> <span aria-hidden="true">›</span> Relatório</nav>
<section class="page-heading"><div><p class="eyebrow">Relatório de Pré-Conselho de Classe</p><h1><?=e($report['turma_nome_snapshot'])?></h1><p><?=e($report['periodo'])?> · <?=e($report['disciplina'])?></p></div><span class="badge status-<?=e(strtolower($report['status']))?>"><?=e($statusLabels[$report['status']]??$report['status'])?></span></section>
<?php if($report['status']==='DEVOLVIDO'):?><p class="error" role="alert"><span aria-hidden="true">!</span><span>Este relatório foi devolvido e precisa de ajustes. Consulte a orientação da coordenação no histórico.</span></p><?php endif;?><?php if($apiError):?><p class="error" role="alert"><span aria-hidden="true">!</span><span><?=e($apiError)?></span></p><?php endif;?>
<form method="post" class="report-sheet"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><input type="hidden" name="versao" value="<?=e($report['versao'])?>">
<section class="card sheet-card"><div class="sheet-title"><span class="brand-mark" aria-hidden="true">PC</span><div><h2>Relatório de Pré-Conselho de Classe</h2><p>Registro pedagógico da turma</p></div></div><dl class="sheet-identity"><div><dt>Turma</dt><dd><?=e($report['turma_nome_snapshot'])?></dd></div><div><dt>Professor(a)</dt><dd><?=e($report['professor_nome'])?></dd></div><div><dt>Disciplina</dt><dd><?=e($report['disciplina'])?></dd></div><div><dt>Data</dt><dd><?=e($reportDate)?></dd></div><div><dt>Período</dt><dd><?=e($report['periodo'])?></dd></div><div><dt>Etapa</dt><dd><?=e($report['etapa'])?></dd></div><div><dt>Número de alunos</dt><dd><?=count($students)?></dd></div><div><dt>Alunos indicados</dt><dd><span id="selected-student-count"><?=count($selected)?></span></dd></div></dl></section>
<section class="card sheet-card"><div class="sheet-section-title"><span>1</span><div><h2>Alunos indicados para o RAV</h2><p>Informe se existem alunos indicados e registre a média atual.</p></div></div><fieldset class="inline-question"><legend>Possui alunos indicados para o RAV?</legend><label><input type="radio" name="possui_alunos_rav" value="1" <?=$report['possui_alunos_rav']==='1'?'checked':''?> <?=!$canEdit?'disabled':''?>> Sim</label><label><input type="radio" name="possui_alunos_rav" value="0" <?=$report['possui_alunos_rav']==='0'?'checked':''?> <?=!$canEdit?'disabled':''?>> Não</label></fieldset>
<?php if($students):?><div class="form-section-header"><div><h3>Relação de alunos</h3><p class="helper">Selecione o aluno e preencha as informações que serão analisadas pela coordenação.</p></div><label class="search"><span class="sr-only">Buscar aluno</span><span aria-hidden="true">⌕</span><input id="student-search" type="search" placeholder="Buscar aluno"></label></div><div class="student-sheet-table table"><table><thead><tr><th class="select-column">Selecionar</th><th>Aluno</th><th class="grade-column">Nota</th><th>Principais dificuldades observadas</th><th>Medidas adotadas pelo professor</th><th>Observações</th></tr></thead><tbody><?php foreach($students as$a):$x=$byId[$a['id']]??[];$chosen=isset($byId[$a['id']]);?><tr data-student-row><td data-label="Selecionar"><input type="checkbox" aria-label="Selecionar <?=e($a['nome_completo'])?>" name="alunos[<?=e($a['id'])?>][selecionado]" value="1" <?=$chosen?'checked':''?> <?=!$canEdit?'disabled':''?>></td><td data-label="Aluno"><strong><?=e($a['nome_completo'])?></strong><input type="hidden" name="alunos[<?=e($a['id'])?>][motivo_rav]" value="<?=e($x['motivo_rav']??'')?>"></td><td data-label="Nota"><input class="student-field student-grade" aria-label="Nota de <?=e($a['nome_completo'])?>" type="number" step="0.1" min="0" max="10" name="alunos[<?=e($a['id'])?>][nota]" value="<?=e($x['nota']??'')?>" <?=$chosen?'':'disabled'?> <?=!$canEdit?'readonly':''?>></td><td data-label="Dificuldades"><textarea class="student-field student-note" aria-label="Principais dificuldades de <?=e($a['nome_completo'])?>" name="alunos[<?=e($a['id'])?>][dificuldades]" placeholder="Descreva as dificuldades" <?=$chosen?'':'disabled'?> <?=!$canEdit?'readonly':''?>><?=e($x['dificuldades']??'')?></textarea></td><td data-label="Medidas adotadas"><textarea class="student-field student-note" aria-label="Medidas adotadas para <?=e($a['nome_completo'])?>" name="alunos[<?=e($a['id'])?>][intervencoes]" placeholder="Descreva as medidas adotadas" <?=$chosen?'':'disabled'?> <?=!$canEdit?'readonly':''?>><?=e($x['intervencoes']??'')?></textarea></td><td data-label="Observações"><textarea class="student-field student-note" aria-label="Observações sobre <?=e($a['nome_completo'])?>" name="alunos[<?=e($a['id'])?>][observacao]" placeholder="Observações adicionais" <?=$chosen?'':'disabled'?> <?=!$canEdit?'readonly':''?>><?=e($x['observacao']??'')?></textarea></td></tr><?php endforeach;?></tbody></table></div><?php elseif(!$apiError):?><div class="empty-state compact"><p>Nenhum aluno encontrado nesta turma.</p></div><?php endif;?></section>
<section class="card sheet-card"><div class="sheet-section-title"><span>2</span><div><h2>Observações feitas na turma</h2><p>Marque todas as situações observadas.</p></div></div><div class="sheet-check-grid"><?php foreach($classObservations as$value=>$label):?><label><input type="checkbox" name="observacoes_turma[]" value="<?=e($value)?>" <?=in_array($value,$checkedObservations,true)?'checked':''?> <?=!$canEdit?'disabled':''?>> <span><?=e($label)?></span></label><?php endforeach;?></div><label>Principais motivos relacionados ao rendimento dos estudantes<textarea name="dificuldades_gerais" <?=!$canEdit?'readonly':''?> placeholder="Descreva os principais motivos identificados"><?=e($report['dificuldades_gerais'])?></textarea></label></section>
<section class="card sheet-card"><div class="sheet-section-title"><span>3</span><div><h2>Medidas adotadas</h2><p>Marque as ações que já foram realizadas.</p></div></div><div class="sheet-check-grid"><?php foreach($adoptedMeasures as$value=>$label):?><label><input type="checkbox" name="medidas_lista[]" value="<?=e($value)?>" <?=in_array($value,$checkedMeasures,true)?'checked':''?> <?=!$canEdit?'disabled':''?>> <span><?=e($label)?></span></label><?php endforeach;?></div><label>Detalhamento das medidas<textarea name="medidas_adotadas" <?=!$canEdit?'readonly':''?> placeholder="Detalhe as ações realizadas e seus resultados"><?=e($report['medidas_adotadas'])?></textarea></label></section>
<section class="card sheet-card"><div class="sheet-section-title"><span>4</span><div><h2>Observações adicionais</h2><p>Registre outras informações relevantes para o Conselho de Classe.</p></div></div><label class="sr-only" for="observacoes_professor">Observações adicionais</label><textarea id="observacoes_professor" name="observacoes_professor" <?=!$canEdit?'readonly':''?> placeholder="Escreva aqui outras informações importantes"><?=e($report['observacoes_professor'])?></textarea><?php if($canEdit):?><div class="actions"><button name="acao" value="rascunho">Salvar para continuar depois</button><button name="acao" value="enviar" class="primary" data-confirm="O relatório será enviado para a coordenação. Deseja continuar?">Enviar para conferência <span aria-hidden="true">→</span></button></div><?php endif;?></section></form>
<?php if($canReview):?><section class="card review-card"><p class="eyebrow">Conferência da coordenação</p><h2>Registrar parecer</h2><p class="helper">Aprove o relatório ou devolva ao professor com uma orientação clara.</p><form method="post" action="/coordenacao/relatorios/<?=e($report['id'])?>"><input type="hidden" name="_csrf" value="<?=e(Csrf::token())?>"><label>Parecer da coordenação<textarea name="parecer" placeholder="Registre o parecer sobre as informações apresentadas"></textarea></label><label>Orientação para devolução<textarea name="justificativa" placeholder="Obrigatória ao devolver: explique o que deve ser corrigido"></textarea></label><div class="actions"><button class="danger" name="acao" value="devolver">Devolver para ajustes</button><button class="primary" name="acao" value="aprovar" data-confirm="Confirma a aprovação deste relatório?">Aprovar relatório</button></div></form></section><?php endif;?>
<section class="card"><p class="eyebrow">Registro</p><h2>Histórico do relatório</h2><?php if(!$history):?><p class="helper">Ainda não há movimentações registradas.</p><?php else:?><ol class="history"><?php foreach($history as$h):?><li><strong><?=e($statusLabels[$h['status_anterior']]??$h['status_anterior'])?> → <?=e($statusLabels[$h['status_novo']]??$h['status_novo'])?></strong><br><small><?=e(date('d/m/Y H:i',strtotime($h['criado_em'])))?> por <?=e($h['usuario_nome'])?></small><?php if(trim((string)$h['justificativa'])!==''):?><p><?=e($h['justificativa'])?></p><?php endif;?></li><?php endforeach;?></ol><?php endif;?></section><?php $content=ob_get_clean();require __DIR__.'/layout.php';
