<?php declare(strict_types=1);
namespace PreConselho\Controllers;
use PreConselho\Integration\SecretariaApiClient;use PreConselho\Repositories\AppRepository;use PreConselho\Support\Csrf;use Shared\Exceptions\HttpException;use Shared\Http\{Request,Response};
final class BindingController
{
 public function __construct(private readonly AppRepository$r,private readonly SecretariaApiClient$api){}
 public function create(Request$q):Response
 {
  Csrf::verify($q->body['_csrf']??null);$userId=filter_var($q->body['professor_id']??null,FILTER_VALIDATE_INT);$classIds=$this->ids($q->body['turma_ids']??[]);$disciplineIds=$this->ids($q->body['disciplina_ids']??[]);if(!$userId||!$classIds||!$disciplineIds||count($classIds)>100||count($disciplineIds)>50)throw new HttpException(422,'VALIDATION_ERROR','Selecione um professor, ao menos uma turma e uma disciplina.');$professor=$this->r->professorByUser((int)$userId);if(!$professor)throw new HttpException(422,'VALIDATION_ERROR','O usuário selecionado não é um professor ativo.');$placeholders=implode(',',array_fill(0,count($disciplineIds),'?'));$s=$this->r->db->prepare("SELECT id FROM disciplinas WHERE ativo=1 AND id IN ($placeholders)");$s->execute($disciplineIds);if(count($s->fetchAll())!==count($disciplineIds))throw new HttpException(422,'VALIDATION_ERROR','Uma das disciplinas selecionadas não está disponível.');$classes=[];foreach($classIds as$classId)$classes[]=$this->api->turma($classId);
  $this->r->db->beginTransaction();$created=0;try{$insert=$this->r->db->prepare('INSERT OR IGNORE INTO vinculos_professor_turma_disciplina(professor_id,turma_externa_id,turma_nome_snapshot,turma_ano_letivo_snapshot,disciplina_id)VALUES(:p,:t,:n,:a,:d)');foreach($classes as$class){foreach($disciplineIds as$discipline){$insert->execute([':p'=>$professor['id'],':t'=>$class['id'],':n'=>$class['nome_turma'],':a'=>$class['ano_letivo'],':d'=>$discipline]);if($insert->rowCount()===0)continue;$created++;$id=(int)$this->r->db->lastInsertId();$this->r->audit($_SESSION['user']['id'],'CRIAR','vinculos_professor_turma_disciplina',$id,null,['professor_id'=>$professor['id'],'turma_externa_id'=>$class['id'],'disciplina_id'=>$discipline],$q->ip(),$q->header('User-Agent')??'');}}$this->r->db->commit();}catch(\Throwable$e){if($this->r->db->inTransaction())$this->r->db->rollBack();throw$e;}$_SESSION['flash']=$created.' vínculo(s) criado(s) com sucesso.'.($created===0?' As combinações selecionadas já existiam.':'');return Response::redirect('/admin#vinculos');
 }
 private function ids(mixed$value):array{if(!is_array($value))return[];$ids=[];foreach($value as$item){$id=filter_var($item,FILTER_VALIDATE_INT,['options'=>['min_range'=>1]]);if($id!==false)$ids[]=(int)$id;}return array_values(array_unique($ids));}
}
