<?php declare(strict_types=1);
namespace PreConselho\Controllers;
use PreConselho\Integration\SecretariaApiClient;use PreConselho\Repositories\AppRepository;use PreConselho\Services\{AuthService,CouncilDocumentService,PeriodService,ReportService};use PreConselho\Support\{CouncilClass,Cpf,Csrf};use Shared\Exceptions\HttpException;use Shared\Http\{Request,Response};use Shared\Support\View;
final class WebController
{
 public function __construct(private readonly AppRepository$r,private readonly View$v,private readonly SecretariaApiClient$api){}
 public function loginForm():Response{return new Response($this->v->render('login',['title'=>'Entrar']));}
 public function login(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$cpf=(string)($q->body['cpf']??'');try{$u=(new AuthService($this->r))->login($cpf,$q->ip(),$q->header('User-Agent')??'');}catch(HttpException$e){return new Response($this->v->render('login',['title'=>'Entrar','loginError'=>$e->getMessage(),'cpfInput'=>$cpf]),$e->status);}session_regenerate_id(true);$_SESSION['user']=['id'=>(int)$u['id'],'nome'=>$u['nome'],'perfil'=>$u['perfil'],'alterar_senha'=>false];return Response::redirect('/');}
 public function logout(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();return Response::redirect('/login');}
 public function dashboard():Response{$u=$_SESSION['user'];$documents=(new CouncilDocumentService($this->r))->summaries((int)$u['id'],$u['perfil']);return new Response($this->v->render('dashboard',compact('documents')+['title'=>'Painel']));}
 public function report(Request$q,array$p):Response{$u=$_SESSION['user'];$report=(new ReportService($this->r,$this->api))->allowed((int)$p['id'],$u['id'],$u['perfil']);return Response::redirect('/documentos/'.$report['periodo_id']);}
 public function document(Request$q,array$p):Response{$u=$_SESSION['user'];$period=(int)$p['periodo'];$document=(new CouncilDocumentService($this->r))->document($period,(int)$u['id'],$u['perfil']);return new Response($this->v->render('document',compact('document','period')+['title'=>'Documento coletivo do conselho']));}
 public function autosaveDocument(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$operations=json_decode((string)($q->body['operacoes']??'[]'),true);if(!is_array($operations))$operations=[];$lockToken=(string)($q->body['lock_token']??'');if($lockToken==='')throw new HttpException(423,'CLASS_LOCK_REQUIRED','Reserve a turma antes de salvar.');$saved=(new CouncilDocumentService($this->r))->saveClass((int)$p['periodo'],(int)$p['turma'],(string)($q->body['conteudo']??''),(int)($q->body['versao']??0),(int)$u['id'],$u['perfil'],$q->ip(),$q->header('User-Agent')??'',$operations,$lockToken);return Response::json(['success'=>true]+$saved);}
 public function lockDocumentClass(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$lock=(new CouncilDocumentService($this->r))->acquireClassLock((int)$p['periodo'],(int)$p['turma'],(int)$u['id'],$u['perfil'],(string)($q->body['lock_token']??''));return Response::json(['success'=>true]+$lock);}
 public function releaseDocumentClass(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new CouncilDocumentService($this->r))->releaseClassLock((int)$p['periodo'],(int)$p['turma'],(int)$u['id'],(string)($q->body['lock_token']??''));return Response::json(['success'=>true]);}
 public function autosaveOpening(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$saved=(new CouncilDocumentService($this->r))->saveOpening((int)$p['periodo'],(string)($q->body['texto']??''),(int)($q->body['versao']??0),(int)$u['id'],$u['perfil']);return Response::json(['success'=>true]+$saved);}
 public function finalizeClass(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$finalize=($q->body['acao']??'finalizar')!=='reabrir';(new CouncilDocumentService($this->r))->finalizeClass((int)$p['periodo'],(int)$p['turma'],(int)$u['id'],$u['perfil'],$finalize,$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']=$finalize?'Turma finalizada. A coordenação já pode ver sua conclusão.':'Sua participação na turma foi reaberta para edição.';return Response::redirect('/documentos/'.(int)$p['periodo'].'#turma-'.(int)$p['turma']);}
 public function reopenClassParticipation(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new CouncilDocumentService($this->r))->reopenParticipation((int)$p['periodo'],(int)$p['turma'],(int)$p['professor'],(int)$u['id'],$u['perfil'],$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']='Edição liberada novamente para o professor.';return Response::redirect('/documentos/'.(int)$p['periodo'].'#turma-'.(int)$p['turma']);}
 public function save(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new ReportService($this->r,$this->api))->save((int)$p['id'],$q->body,$u['id'],$u['perfil'],($q->body['acao']??'')==='enviar',$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']='Relatório atualizado com sucesso.';return Response::redirect('/relatorios/'.$p['id']);}
 public function autosave(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new ReportService($this->r,$this->api))->save((int)$p['id'],$q->body,$u['id'],$u['perfil'],false,$q->ip(),$q->header('User-Agent')??'',true);$fresh=$this->r->report((int)$p['id']);return Response::json(['success'=>true,'version'=>(int)$fresh['versao'],'saved_at'=>date('H:i')]);}
 public function review(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$common=is_array($q->body['motivos']??null)?$q->body['motivos']:[];$reason=trim(implode('; ',array_map('strval',$common)).' '.(string)($q->body['justificativa']??''));(new ReportService($this->r,$this->api))->review((int)$p['id'],($q->body['acao']??'')==='aprovar',$reason,(string)($q->body['parecer']??''),(string)($q->body['orientacao_coordenacao']??''),$u['id'],$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']=($q->body['acao']??'')==='aprovar'?'Relatório aprovado.':'Relatório devolvido com orientação.';return Response::redirect('/conselho');}
 public function passwordForm():Response{return Response::redirect('/');}
 public function changePassword(Request$q):Response{Csrf::verify($q->body['_csrf']??null);return Response::redirect('/');}
 public function period(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new PeriodService($this->r))->create($q->body,$u['id'],$q->ip(),$q->header('User-Agent')??'');return Response::redirect('/admin#periodos');}
 public function periodAction(Request$q,array$p,string$action):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$svc=new PeriodService($this->r);$action==='open'?$svc->open((int)$p['id'],$u['id'],$q->ip(),$q->header('User-Agent')??''):$svc->close((int)$p['id'],$u['id'],$q->ip(),$q->header('User-Agent')??'');return Response::redirect('/admin#periodos');}
 public function admin():Response{$users=$this->r->db->query('SELECT id,nome,cpf,perfil,ativo FROM usuarios WHERE excluido_em IS NULL ORDER BY nome')->fetchAll();$professors=$this->r->db->query("SELECT u.id,u.nome,u.cpf FROM usuarios u JOIN professores p ON p.usuario_id=u.id WHERE u.ativo=1 AND u.excluido_em IS NULL AND p.ativo=1 ORDER BY u.nome")->fetchAll();$periods=$this->r->db->query('SELECT * FROM periodos_pre_conselho ORDER BY ano_letivo DESC,id DESC')->fetchAll();$bindings=$this->r->db->query("SELECT v.*,u.id usuario_id,u.nome professor_nome FROM vinculos_professor_turma v JOIN professores p ON p.id=v.professor_id JOIN usuarios u ON u.id=p.usuario_id ORDER BY u.nome,v.turno,v.turma_nome_snapshot")->fetchAll();$unboundCount=(int)$this->r->db->query("SELECT COUNT(*) FROM professores p JOIN usuarios u ON u.id=p.usuario_id WHERE p.ativo=1 AND u.ativo=1 AND u.excluido_em IS NULL AND NOT EXISTS(SELECT 1 FROM vinculos_professor_turma v WHERE v.professor_id=p.id AND v.ativo=1)")->fetchColumn();$classes=[];$classesError=null;try{$classes=$this->api->turmas();}catch(\Throwable){$classesError='Não foi possível carregar as turmas da secretaria neste momento.';}return new Response($this->v->render('admin',compact('users','professors','periods','bindings','unboundCount','classes','classesError')+['title'=>'Administração']));}
 public function createUser(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$name=trim((string)($q->body['nome']??''));$cpf=Cpf::normalize($q->body['cpf']??'');$role=(string)($q->body['perfil']??'');if($name===''||mb_strlen($name)>150||!Cpf::isValid($cpf)||!in_array($role,['ADMIN','COORDENADOR','PROFESSOR'],true))throw new HttpException(422,'VALIDATION_ERROR','Confira o nome, o CPF e o tipo de acesso.');$this->r->db->beginTransaction();try{$email='cpf-'.$cpf.'@usuario.local';$hash=password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT);$s=$this->r->db->prepare('INSERT INTO usuarios(nome,email,cpf,senha_hash,perfil,alterar_senha)VALUES(:n,:e,:cpf,:s,:p,0)');$s->execute([':n'=>$name,':e'=>$email,':cpf'=>$cpf,':s'=>$hash,':p'=>$role]);$id=(int)$this->r->db->lastInsertId();if($role==='PROFESSOR')$this->r->db->prepare('INSERT INTO professores(usuario_id)VALUES(:u)')->execute([':u'=>$id]);$this->r->audit($_SESSION['user']['id'],'CRIAR','usuarios',$id,null,['nome'=>$name,'cpf'=>Cpf::format($cpf),'perfil'=>$role],$q->ip(),$q->header('User-Agent')??'');$this->r->db->commit();}catch(\PDOException$e){if($this->r->db->inTransaction())$this->r->db->rollBack();if($e->getCode()==='23000')throw new HttpException(422,'CPF_IN_USE','Este CPF já está sendo utilizado.');throw$e;}catch(\Throwable$e){if($this->r->db->inTransaction())$this->r->db->rollBack();throw$e;}$_SESSION['flash']='Usuário criado. O acesso será feito apenas com o CPF.';return Response::redirect('/admin#usuarios');}
 public function consolidated(Request$q):Response{$rows=$this->r->db->query("SELECT p.id periodo_id,p.nome periodo,p.ano_letivo,p.turno,dt.turma_nome_snapshot turma,dt.conteudo relato,COALESCE(u.nome,'—') atualizado_por,dt.atualizado_em FROM documento_turmas dt JOIN periodos_pre_conselho p ON p.id=dt.periodo_id LEFT JOIN usuarios u ON u.id=dt.atualizado_por WHERE TRIM(dt.conteudo)<>''")->fetchAll();foreach($rows as&$row){$identity=CouncilClass::identify((string)$row['turma']);$row['turma']=$identity['name'];$row['_ordem_turma']=$identity['order'];}unset($row);usort($rows,static function(array$a,array$b):int{return((int)$b['ano_letivo']<=>(int)$a['ano_letivo'])?:((int)$b['periodo_id']<=>(int)$a['periodo_id'])?:((int)$a['_ordem_turma']<=>(int)$b['_ordem_turma'])?:strnatcasecmp($a['turma'],$b['turma']);});foreach($rows as&$row){unset($row['periodo_id'],$row['_ordem_turma']);}unset($row);if(($q->query['formato']??'')==='csv'){$out=fopen('php://temp','r+');fputcsv($out,['Período','Ano letivo','Turno','Turma','Relato coletivo','Última atualização por','Atualizado em']);foreach($rows as$x)fputcsv($out,array_values($x));rewind($out);return new Response((string)stream_get_contents($out),200,['Content-Type'=>'text/csv; charset=utf-8','Content-Disposition'=>'attachment; filename="conselho-coletivo.csv"']);}return new Response($this->v->render('consolidated',compact('rows')+['title'=>'Documento coletivo']));}
}
