<?php declare(strict_types=1);
namespace PreConselho\Controllers;
use PreConselho\Integration\SecretariaApiClient;use PreConselho\Repositories\AppRepository;use PreConselho\Services\{AuthService,PeriodService,ReportService};use PreConselho\Support\Csrf;use Shared\Exceptions\HttpException;use Shared\Http\{Request,Response};use Shared\Support\View;
final class WebController
{
 public function __construct(private readonly AppRepository$r,private readonly View$v,private readonly SecretariaApiClient$api){}
 public function loginForm():Response{return new Response($this->v->render('login',['title'=>'Entrar']));}
 public function login(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$u=(new AuthService($this->r))->login((string)($q->body['email']??''),(string)($q->body['senha']??''),$q->ip(),$q->header('User-Agent')??'');session_regenerate_id(true);$_SESSION['user']=['id'=>(int)$u['id'],'nome'=>$u['nome'],'perfil'=>$u['perfil'],'alterar_senha'=>(bool)($u['alterar_senha']??false)];return Response::redirect(!empty($u['alterar_senha'])?'/minha-senha':'/');}
 public function logout(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();return Response::redirect('/login');}
 public function dashboard():Response{$u=$_SESSION['user'];$reports=$u['perfil']==='PROFESSOR'?$this->r->professorReports($u['id']):$this->r->coordinationReports();$counts=array_fill_keys(['PENDENTE','RASCUNHO','ENVIADO','DEVOLVIDO','APROVADO'],0);$professorProgress=[];foreach($reports as$x){$counts[$x['status']]++;if($u['perfil']!=='PROFESSOR'){$name=$x['professor_nome'];$professorProgress[$name]??=['nome'=>$name,'total'=>0,'pendentes'=>0,'enviados'=>0,'aprovados'=>0,'reports'=>[]];$professorProgress[$name]['total']++;$professorProgress[$name]['reports'][]=$x;if(in_array($x['status'],['PENDENTE','RASCUNHO','DEVOLVIDO'],true))$professorProgress[$name]['pendentes']++;elseif($x['status']==='ENVIADO')$professorProgress[$name]['enviados']++;elseif($x['status']==='APROVADO')$professorProgress[$name]['aprovados']++;}}ksort($professorProgress,SORT_NATURAL|SORT_FLAG_CASE);return new Response($this->v->render('dashboard',compact('reports','counts','professorProgress')+['title'=>'Painel']));}
 public function report(Request$q,array$p):Response{$u=$_SESSION['user'];$svc=new ReportService($this->r,$this->api);$report=$svc->allowed((int)$p['id'],$u['id'],$u['perfil']);$selected=$this->r->reportStudents((int)$p['id']);$history=$this->r->history((int)$p['id']);$students=[];$apiError=null;try{$students=$this->api->alunosDaTurma((int)$report['turma_externa_id']);}catch(\Throwable){$apiError='A lista atual de alunos está temporariamente indisponível. Os dados já salvos continuam disponíveis.';}$known=array_fill_keys(array_map(static fn(array$x):int=>(int)$x['id'],$students),true);foreach($selected as$item)if(!isset($known[(int)$item['aluno_externo_id']]))$students[]=['id'=>(int)$item['aluno_externo_id'],'nome_completo'=>$item['aluno_nome_snapshot'],'data_nascimento'=>$item['aluno_data_nascimento_snapshot'],'id_turma'=>(int)$report['turma_externa_id']];if($u['perfil']!=='PROFESSOR'){$selectedIds=array_fill_keys(array_map(static fn(array$x):int=>(int)$x['aluno_externo_id'],$selected),true);$students=array_values(array_filter($students,static fn(array$x):bool=>isset($selectedIds[(int)$x['id']])));}usort($students,static fn(array$a,array$b):int=>strnatcasecmp($a['nome_completo'],$b['nome_completo']));return new Response($this->v->render('report',compact('report','selected','history','students','apiError')+['title'=>'Relatório']));}
 public function save(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new ReportService($this->r,$this->api))->save((int)$p['id'],$q->body,$u['id'],$u['perfil'],($q->body['acao']??'')==='enviar',$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']='Relatório atualizado com sucesso.';return Response::redirect('/relatorios/'.$p['id']);}
 public function autosave(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new ReportService($this->r,$this->api))->save((int)$p['id'],$q->body,$u['id'],$u['perfil'],false,$q->ip(),$q->header('User-Agent')??'',true);$fresh=$this->r->report((int)$p['id']);return Response::json(['success'=>true,'version'=>(int)$fresh['versao'],'saved_at'=>date('H:i')]);}
 public function review(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$common=is_array($q->body['motivos']??null)?$q->body['motivos']:[];$reason=trim(implode('; ',array_map('strval',$common)).' '.(string)($q->body['justificativa']??''));(new ReportService($this->r,$this->api))->review((int)$p['id'],($q->body['acao']??'')==='aprovar',$reason,(string)($q->body['parecer']??''),(string)($q->body['orientacao_coordenacao']??''),$u['id'],$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']=($q->body['acao']??'')==='aprovar'?'Relatório aprovado.':'Relatório devolvido com orientação.';return Response::redirect('/');}
 public function passwordForm():Response{return new Response($this->v->render('password',['title'=>'Minha senha']));}
 public function changePassword(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$id=(int)$_SESSION['user']['id'];$current=(string)($q->body['senha_atual']??'');$new=(string)($q->body['nova_senha']??'');$confirm=(string)($q->body['confirmar_senha']??'');$s=$this->r->db->prepare('SELECT senha_hash FROM usuarios WHERE id=:id');$s->execute([':id'=>$id]);$u=$s->fetch();if(!$u||!password_verify($current,$u['senha_hash']))throw new HttpException(422,'PASSWORD_INVALID','A senha atual não confere.');if(strlen($new)<10||$new!==$confirm)throw new HttpException(422,'PASSWORD_REQUIREMENTS','A nova senha deve ter ao menos 10 caracteres e a confirmação deve ser igual.');$this->r->db->beginTransaction();try{$this->r->db->prepare('UPDATE usuarios SET senha_hash=:senha,alterar_senha=0,atualizado_em=CURRENT_TIMESTAMP WHERE id=:id')->execute([':senha'=>password_hash($new,PASSWORD_DEFAULT),':id'=>$id]);$this->r->audit($id,'ALTERAR_SENHA','usuarios',$id,null,['senha_alterada'=>true],$q->ip(),$q->header('User-Agent')??'');$this->r->db->commit();}catch(\Throwable$e){if($this->r->db->inTransaction())$this->r->db->rollBack();throw$e;}$_SESSION['user']['alterar_senha']=false;$_SESSION['flash']='Senha alterada com sucesso.';return Response::redirect('/');}
 public function period(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$id=(new PeriodService($this->r))->create($q->body,$u['id'],$q->ip(),$q->header('User-Agent')??'');return Response::redirect('/admin?periodo='.$id);}
 public function periodAction(Request$q,array$p,string$action):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$svc=new PeriodService($this->r);$action==='open'?$svc->open((int)$p['id'],$u['id'],$q->ip(),$q->header('User-Agent')??''):$svc->close((int)$p['id'],$u['id'],$q->ip(),$q->header('User-Agent')??'');return Response::redirect('/admin');}
 public function admin():Response{$users=$this->r->db->query('SELECT id,nome,email,perfil,ativo FROM usuarios WHERE excluido_em IS NULL ORDER BY nome')->fetchAll();$professors=$this->r->db->query("SELECT u.id,u.nome,u.email FROM usuarios u JOIN professores p ON p.usuario_id=u.id WHERE u.ativo=1 AND u.excluido_em IS NULL AND p.ativo=1 ORDER BY u.nome")->fetchAll();$disciplines=$this->r->db->query('SELECT d.*,COUNT(v.id) vinculos FROM disciplinas d LEFT JOIN vinculos_professor_turma_disciplina v ON v.disciplina_id=d.id GROUP BY d.id ORDER BY d.nome')->fetchAll();$periods=$this->r->db->query('SELECT * FROM periodos_pre_conselho ORDER BY ano_letivo DESC,id DESC')->fetchAll();$bindings=$this->r->db->query("SELECT v.*,u.id usuario_id,u.nome professor_nome,d.nome disciplina_nome,COUNT(r.id) relatorios FROM vinculos_professor_turma_disciplina v JOIN professores p ON p.id=v.professor_id JOIN usuarios u ON u.id=p.usuario_id JOIN disciplinas d ON d.id=v.disciplina_id LEFT JOIN relatorios_pre_conselho r ON r.vinculo_id=v.id GROUP BY v.id ORDER BY u.nome,v.turma_nome_snapshot,d.nome")->fetchAll();$bindingCount=(int)$this->r->db->query('SELECT COUNT(*) FROM vinculos_professor_turma_disciplina WHERE ativo=1')->fetchColumn();$unboundCount=(int)$this->r->db->query("SELECT COUNT(*) FROM professores p JOIN usuarios u ON u.id=p.usuario_id WHERE p.ativo=1 AND u.ativo=1 AND u.excluido_em IS NULL AND NOT EXISTS(SELECT 1 FROM vinculos_professor_turma_disciplina v WHERE v.professor_id=p.id AND v.ativo=1)")->fetchColumn();$classes=[];$classesError=null;try{$classes=$this->api->turmas();}catch(\Throwable){$classesError='Não foi possível carregar as turmas da secretaria neste momento.';}return new Response($this->v->render('admin',compact('users','professors','disciplines','periods','bindings','bindingCount','unboundCount','classes','classesError')+['title'=>'Administração']));}
 public function createUser(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$name=trim((string)($q->body['nome']??''));$email=filter_var($q->body['email']??'',FILTER_VALIDATE_EMAIL);$role=$q->body['perfil']??'';$pass=(string)($q->body['senha']??'');if($name===''||!$email||!in_array($role,['ADMIN','COORDENADOR','PROFESSOR'],true)||strlen($pass)<10)throw new HttpException(422,'VALIDATION_ERROR','Dados de usuário inválidos; a senha deve ter ao menos 10 caracteres.');$this->r->db->beginTransaction();try{$s=$this->r->db->prepare('INSERT INTO usuarios(nome,email,senha_hash,perfil,alterar_senha)VALUES(:n,:e,:s,:p,1)');$s->execute([':n'=>$name,':e'=>mb_strtolower($email),':s'=>password_hash($pass,PASSWORD_DEFAULT),':p'=>$role]);$id=(int)$this->r->db->lastInsertId();if($role==='PROFESSOR')$this->r->db->prepare('INSERT INTO professores(usuario_id)VALUES(:u)')->execute([':u'=>$id]);$this->r->audit($_SESSION['user']['id'],'CRIAR','usuarios',$id,null,['nome'=>$name,'email'=>$email,'perfil'=>$role],$q->ip(),$q->header('User-Agent')??'');$this->r->db->commit();}catch(\Throwable$e){if($this->r->db->inTransaction())$this->r->db->rollBack();throw$e;}$_SESSION['flash']='Usuário criado. A senha deverá ser alterada no primeiro acesso.';return Response::redirect('/admin');}
 public function createDiscipline(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$name=trim((string)($q->body['nome']??''));if($name===''||mb_strlen($name)>100)throw new HttpException(422,'VALIDATION_ERROR','Disciplina inválida.');$this->r->db->prepare('INSERT INTO disciplinas(nome)VALUES(:n)')->execute([':n'=>$name]);return Response::redirect('/admin');}
 public function consolidated(Request$q):Response{$rows=$this->r->db->query("SELECT ra.aluno_nome_snapshot aluno,v.turma_nome_snapshot turma,d.nome disciplina,u.nome professor,ra.nota,ra.dificuldades,ra.intervencoes FROM relatorio_alunos ra JOIN relatorios_pre_conselho r ON r.id=ra.relatorio_id JOIN vinculos_professor_turma_disciplina v ON v.id=r.vinculo_id JOIN disciplinas d ON d.id=v.disciplina_id JOIN professores p ON p.id=v.professor_id JOIN usuarios u ON u.id=p.usuario_id WHERE r.status='APROVADO' ORDER BY v.turma_nome_snapshot,ra.aluno_nome_snapshot")->fetchAll();if(($q->query['formato']??'')==='csv'){$out=fopen('php://temp','r+');fputcsv($out,['Aluno','Turma','Disciplina','Professor','Nota','Dificuldades','Intervenções']);foreach($rows as$x)fputcsv($out,array_values($x));rewind($out);return new Response((string)stream_get_contents($out),200,['Content-Type'=>'text/csv; charset=utf-8','Content-Disposition'=>'attachment; filename="consolidado.csv"']);}return new Response($this->v->render('consolidated',compact('rows')+['title'=>'Consolidado']));}
}
