<?php declare(strict_types=1);
namespace PreConselho\Controllers;
use PreConselho\Integration\SecretariaApiClient;use PreConselho\Repositories\AppRepository;use PreConselho\Services\{AuthService,CouncilDocumentService,PeriodService,ReportService};use PreConselho\Support\{Cpf,Csrf};use Shared\Exceptions\HttpException;use Shared\Http\{Request,Response};use Shared\Support\View;
final class WebController
{
 public function __construct(private readonly AppRepository$r,private readonly View$v,private readonly SecretariaApiClient$api){}
 public function loginForm():Response{return new Response($this->v->render('login',['title'=>'Entrar']));}
 public function login(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$cpf=(string)($q->body['cpf']??'');try{$u=(new AuthService($this->r))->login($cpf,$q->ip(),$q->header('User-Agent')??'');}catch(HttpException$e){return new Response($this->v->render('login',['title'=>'Entrar','loginError'=>$e->getMessage(),'cpfInput'=>$cpf]),$e->status);}session_regenerate_id(true);$_SESSION['user']=['id'=>(int)$u['id'],'nome'=>$u['nome'],'perfil'=>$u['perfil'],'alterar_senha'=>false];return Response::redirect('/');}
 public function logout(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$_SESSION=[];if(ini_get('session.use_cookies')){$p=session_get_cookie_params();setcookie(session_name(),'',time()-42000,$p['path'],$p['domain'],$p['secure'],$p['httponly']);}session_destroy();return Response::redirect('/login');}
 public function dashboard():Response{$u=$_SESSION['user'];$reports=$u['perfil']==='PROFESSOR'?$this->r->professorReports($u['id']):$this->r->coordinationReports();$documents=$this->groupDocuments($reports);return new Response($this->v->render('dashboard',compact('documents')+['title'=>'Painel']));}
 public function report(Request$q,array$p):Response{$u=$_SESSION['user'];$report=(new ReportService($this->r,$this->api))->allowed((int)$p['id'],$u['id'],$u['perfil']);$url='/documentos/'.$report['periodo_id'];if($u['perfil']!=='PROFESSOR')$url.='/professores/'.$report['professor_usuario_id'];return Response::redirect($url);}
 public function document(Request$q,array$p):Response{$u=$_SESSION['user'];$period=(int)$p['periodo'];$professor=$u['perfil']==='PROFESSOR'?(int)$u['id']:(int)($p['professor']??0);$svc=new CouncilDocumentService($this->r);$reports=$svc->allowed($period,$professor,(int)$u['id'],$u['perfil']);$history=$this->r->documentHistory($period,$professor);$status=$this->documentStatus($reports);return new Response($this->v->render('document',compact('reports','history','status','professor','period')+['title'=>'Documento do conselho']));}
 public function saveDocument(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$period=(int)$p['periodo'];$submit=($q->body['acao']??'')==='enviar';(new CouncilDocumentService($this->r))->save($period,(int)$u['id'],$q->body,(int)$u['id'],$u['perfil'],$submit,$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']=$submit?'Documento enviado para a coordenação.':'Documento salvo para continuar depois.';return Response::redirect('/documentos/'.$period);}
 public function autosaveDocument(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$versions=(new CouncilDocumentService($this->r))->save((int)$p['periodo'],(int)$u['id'],$q->body,(int)$u['id'],$u['perfil'],false,$q->ip(),$q->header('User-Agent')??'',true);return Response::json(['success'=>true,'versions'=>$versions,'saved_at'=>date('H:i')]);}
 public function reviewDocument(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$common=is_array($q->body['motivos']??null)?$q->body['motivos']:[];$reason=trim(implode('; ',array_map('strval',$common)).' '.(string)($q->body['justificativa']??''));$approve=($q->body['acao']??'')==='aprovar';(new CouncilDocumentService($this->r))->review((int)$p['periodo'],(int)$p['professor'],$approve,$reason,(string)($q->body['parecer']??''),(int)$u['id'],$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']=$approve?'Documento aprovado.':'Documento devolvido ao professor.';return Response::redirect('/');}
 public function save(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new ReportService($this->r,$this->api))->save((int)$p['id'],$q->body,$u['id'],$u['perfil'],($q->body['acao']??'')==='enviar',$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']='Relatório atualizado com sucesso.';return Response::redirect('/relatorios/'.$p['id']);}
 public function autosave(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];(new ReportService($this->r,$this->api))->save((int)$p['id'],$q->body,$u['id'],$u['perfil'],false,$q->ip(),$q->header('User-Agent')??'',true);$fresh=$this->r->report((int)$p['id']);return Response::json(['success'=>true,'version'=>(int)$fresh['versao'],'saved_at'=>date('H:i')]);}
 public function review(Request$q,array$p):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$common=is_array($q->body['motivos']??null)?$q->body['motivos']:[];$reason=trim(implode('; ',array_map('strval',$common)).' '.(string)($q->body['justificativa']??''));(new ReportService($this->r,$this->api))->review((int)$p['id'],($q->body['acao']??'')==='aprovar',$reason,(string)($q->body['parecer']??''),(string)($q->body['orientacao_coordenacao']??''),$u['id'],$q->ip(),$q->header('User-Agent')??'');$_SESSION['flash']=($q->body['acao']??'')==='aprovar'?'Relatório aprovado.':'Relatório devolvido com orientação.';return Response::redirect('/');}
 public function passwordForm():Response{return Response::redirect('/');}
 public function changePassword(Request$q):Response{Csrf::verify($q->body['_csrf']??null);return Response::redirect('/');}
 public function period(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$id=(new PeriodService($this->r))->create($q->body,$u['id'],$q->ip(),$q->header('User-Agent')??'');return Response::redirect('/admin?periodo='.$id);}
 public function periodAction(Request$q,array$p,string$action):Response{Csrf::verify($q->body['_csrf']??null);$u=$_SESSION['user'];$svc=new PeriodService($this->r);$action==='open'?$svc->open((int)$p['id'],$u['id'],$q->ip(),$q->header('User-Agent')??''):$svc->close((int)$p['id'],$u['id'],$q->ip(),$q->header('User-Agent')??'');return Response::redirect('/admin');}
 public function admin():Response{$users=$this->r->db->query('SELECT id,nome,cpf,perfil,ativo FROM usuarios WHERE excluido_em IS NULL ORDER BY nome')->fetchAll();$professors=$this->r->db->query("SELECT u.id,u.nome,u.cpf FROM usuarios u JOIN professores p ON p.usuario_id=u.id WHERE u.ativo=1 AND u.excluido_em IS NULL AND p.ativo=1 ORDER BY u.nome")->fetchAll();$disciplines=$this->r->db->query('SELECT d.*,COUNT(v.id) vinculos FROM disciplinas d LEFT JOIN vinculos_professor_turma_disciplina v ON v.disciplina_id=d.id GROUP BY d.id ORDER BY d.nome')->fetchAll();$periods=$this->r->db->query('SELECT * FROM periodos_pre_conselho ORDER BY ano_letivo DESC,id DESC')->fetchAll();$bindings=$this->r->db->query("SELECT v.*,u.id usuario_id,u.nome professor_nome,d.nome disciplina_nome,COUNT(r.id) relatorios FROM vinculos_professor_turma_disciplina v JOIN professores p ON p.id=v.professor_id JOIN usuarios u ON u.id=p.usuario_id JOIN disciplinas d ON d.id=v.disciplina_id LEFT JOIN relatorios_pre_conselho r ON r.vinculo_id=v.id GROUP BY v.id ORDER BY u.nome,v.turma_nome_snapshot,d.nome")->fetchAll();$bindingCount=(int)$this->r->db->query('SELECT COUNT(*) FROM vinculos_professor_turma_disciplina WHERE ativo=1')->fetchColumn();$unboundCount=(int)$this->r->db->query("SELECT COUNT(*) FROM professores p JOIN usuarios u ON u.id=p.usuario_id WHERE p.ativo=1 AND u.ativo=1 AND u.excluido_em IS NULL AND NOT EXISTS(SELECT 1 FROM vinculos_professor_turma_disciplina v WHERE v.professor_id=p.id AND v.ativo=1)")->fetchColumn();$classes=[];$classesError=null;try{$classes=$this->api->turmas();}catch(\Throwable){$classesError='Não foi possível carregar as turmas da secretaria neste momento.';}return new Response($this->v->render('admin',compact('users','professors','disciplines','periods','bindings','bindingCount','unboundCount','classes','classesError')+['title'=>'Administração']));}
 public function createUser(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$name=trim((string)($q->body['nome']??''));$cpf=Cpf::normalize($q->body['cpf']??'');$role=(string)($q->body['perfil']??'');if($name===''||mb_strlen($name)>150||!Cpf::isValid($cpf)||!in_array($role,['ADMIN','COORDENADOR','PROFESSOR'],true))throw new HttpException(422,'VALIDATION_ERROR','Confira o nome, o CPF e o tipo de acesso.');$this->r->db->beginTransaction();try{$email='cpf-'.$cpf.'@usuario.local';$hash=password_hash(bin2hex(random_bytes(32)),PASSWORD_DEFAULT);$s=$this->r->db->prepare('INSERT INTO usuarios(nome,email,cpf,senha_hash,perfil,alterar_senha)VALUES(:n,:e,:cpf,:s,:p,0)');$s->execute([':n'=>$name,':e'=>$email,':cpf'=>$cpf,':s'=>$hash,':p'=>$role]);$id=(int)$this->r->db->lastInsertId();if($role==='PROFESSOR')$this->r->db->prepare('INSERT INTO professores(usuario_id)VALUES(:u)')->execute([':u'=>$id]);$this->r->audit($_SESSION['user']['id'],'CRIAR','usuarios',$id,null,['nome'=>$name,'cpf'=>Cpf::format($cpf),'perfil'=>$role],$q->ip(),$q->header('User-Agent')??'');$this->r->db->commit();}catch(\PDOException$e){if($this->r->db->inTransaction())$this->r->db->rollBack();if($e->getCode()==='23000')throw new HttpException(422,'CPF_IN_USE','Este CPF já está sendo utilizado.');throw$e;}catch(\Throwable$e){if($this->r->db->inTransaction())$this->r->db->rollBack();throw$e;}$_SESSION['flash']='Usuário criado. O acesso será feito apenas com o CPF.';return Response::redirect('/admin');}
 public function createDiscipline(Request$q):Response{Csrf::verify($q->body['_csrf']??null);$name=trim((string)($q->body['nome']??''));if($name===''||mb_strlen($name)>100)throw new HttpException(422,'VALIDATION_ERROR','Disciplina inválida.');$this->r->db->prepare('INSERT INTO disciplinas(nome)VALUES(:n)')->execute([':n'=>$name]);return Response::redirect('/admin');}
 public function consolidated(Request$q):Response{$rows=$this->r->db->query("SELECT pp.nome periodo,pp.ano_letivo,v.turma_nome_snapshot turma,d.nome disciplina,u.nome professor,r.observacoes_professor relato FROM relatorios_pre_conselho r JOIN periodos_pre_conselho pp ON pp.id=r.periodo_id JOIN vinculos_professor_turma_disciplina v ON v.id=r.vinculo_id JOIN disciplinas d ON d.id=v.disciplina_id JOIN professores p ON p.id=v.professor_id JOIN usuarios u ON u.id=p.usuario_id WHERE r.status='APROVADO' ORDER BY pp.ano_letivo DESC,pp.id DESC,v.turma_nome_snapshot,u.nome,d.nome")->fetchAll();if(($q->query['formato']??'')==='csv'){$out=fopen('php://temp','r+');fputcsv($out,['Período','Ano letivo','Turma','Disciplina','Professor','Relato']);foreach($rows as$x)fputcsv($out,array_values($x));rewind($out);return new Response((string)stream_get_contents($out),200,['Content-Type'=>'text/csv; charset=utf-8','Content-Disposition'=>'attachment; filename="consolidado-conselho.csv"']);}return new Response($this->v->render('consolidated',compact('rows')+['title'=>'Consolidado']));}
 private function groupDocuments(array$reports):array{$groups=[];foreach($reports as$report){$professor=(int)($report['professor_usuario_id']??$_SESSION['user']['id']);$key=$report['periodo_id'].'|'.$professor;$groups[$key]??=['periodo_id'=>(int)$report['periodo_id'],'periodo'=>$report['periodo'],'ano_letivo'=>(int)$report['ano_letivo'],'data_fim'=>$report['data_fim'],'periodo_status'=>$report['periodo_status'],'professor_usuario_id'=>$professor,'professor_nome'=>$report['professor_nome']??$_SESSION['user']['nome'],'reports'=>[]];$groups[$key]['reports'][]=$report;}foreach($groups as&$document){$document['status']=$this->documentStatus($document['reports']);$document['turmas']=count(array_unique(array_column($document['reports'],'turma_nome_snapshot')));$document['preenchidas']=count(array_filter($document['reports'],static fn(array$r):bool=>trim((string)($r['observacoes_professor']??''))!==''));}unset($document);$groups=array_values($groups);usort($groups,static fn(array$a,array$b):int=>[$a['periodo_status']==='ABERTO'?0:1,$a['data_fim'],$a['professor_nome']]<=>[$b['periodo_status']==='ABERTO'?0:1,$b['data_fim'],$b['professor_nome']]);return$groups;}
 private function documentStatus(array$reports):string{$statuses=array_column($reports,'status');if($statuses!==[]&&count(array_filter($statuses,static fn(string$s):bool=>$s==='APROVADO'))===count($statuses))return'APROVADO';if(in_array('DEVOLVIDO',$statuses,true))return'DEVOLVIDO';if($statuses!==[]&&count(array_filter($statuses,static fn(string$s):bool=>$s==='ENVIADO'))===count($statuses))return'ENVIADO';foreach($reports as$report)if($report['status']==='RASCUNHO'||trim((string)($report['observacoes_professor']??''))!=='')return'RASCUNHO';return'PENDENTE';}
}
